# Generated by Google APIs Discovery Generator for run (v2)
# Do not edit directly.

require "../../client"
require "../../auth"
require "./projects_locations_service"
require "./projects_locations_operations_service"
require "./projects_locations_worker_pools_service"
require "./projects_locations_worker_pools_revisions_service"
require "./projects_locations_builds_service"
require "./projects_locations_instances_service"
require "./projects_locations_source_uploads_service"
require "./projects_locations_services_service"
require "./projects_locations_services_revisions_service"
require "./projects_locations_jobs_service"
require "./projects_locations_jobs_executions_service"
require "./projects_locations_jobs_executions_tasks_service"

module GoogleApis::Run::V2
  # Client for the Cloud Run Admin API API (v2).
  class Client
    DEFAULT_BASE_URL = "https://run.googleapis.com/"

    getter client : GoogleApis::Client
    getter projects_locations : ProjectsLocationsService
    getter projects_locations_operations : ProjectsLocationsOperationsService
    getter projects_locations_worker_pools : ProjectsLocationsWorkerPoolsService
    getter projects_locations_worker_pools_revisions : ProjectsLocationsWorkerPoolsRevisionsService
    getter projects_locations_builds : ProjectsLocationsBuildsService
    getter projects_locations_instances : ProjectsLocationsInstancesService
    getter projects_locations_source_uploads : ProjectsLocationsSourceUploadsService
    getter projects_locations_services : ProjectsLocationsServicesService
    getter projects_locations_services_revisions : ProjectsLocationsServicesRevisionsService
    getter projects_locations_jobs : ProjectsLocationsJobsService
    getter projects_locations_jobs_executions : ProjectsLocationsJobsExecutionsService
    getter projects_locations_jobs_executions_tasks : ProjectsLocationsJobsExecutionsTasksService

    def initialize(
      credentials : GoogleApis::Auth::Credentials,
      base_url : String = DEFAULT_BASE_URL,
    )
      @client = GoogleApis::Client.new(credentials, base_url)
      @projects_locations = ProjectsLocationsService.new(@client)
      @projects_locations_operations = ProjectsLocationsOperationsService.new(@client)
      @projects_locations_worker_pools = ProjectsLocationsWorkerPoolsService.new(@client)
      @projects_locations_worker_pools_revisions = ProjectsLocationsWorkerPoolsRevisionsService.new(@client)
      @projects_locations_builds = ProjectsLocationsBuildsService.new(@client)
      @projects_locations_instances = ProjectsLocationsInstancesService.new(@client)
      @projects_locations_source_uploads = ProjectsLocationsSourceUploadsService.new(@client)
      @projects_locations_services = ProjectsLocationsServicesService.new(@client)
      @projects_locations_services_revisions = ProjectsLocationsServicesRevisionsService.new(@client)
      @projects_locations_jobs = ProjectsLocationsJobsService.new(@client)
      @projects_locations_jobs_executions = ProjectsLocationsJobsExecutionsService.new(@client)
      @projects_locations_jobs_executions_tasks = ProjectsLocationsJobsExecutionsTasksService.new(@client)
    end
  end
end
