# Generated by Google APIs Discovery Generator for run (v2)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Run::V2
  class ProjectsLocationsOperationsService < GoogleApis::Service
    # Waits until the specified long-running operation is done or reaches at most a specified timeout, returning the latest state. If the operation is already done, the latest state is immediately returned. If the timeout specified is greater than the default HTTP/RPC timeout, the HTTP/RPC timeout is used. If the server does not support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Note that this method is on a best-effort basis. It may return the latest state before the specified timeout (including immediately), meaning even an immediate response is no guarantee that the operation is done.
    def wait(
      name : String,
      body : GoogleLongrunningWaitOperationRequest? = nil,
    ) : GoogleLongrunningOperation
      req_path = "v2/{+name}:wait"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleLongrunningOperation,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.
    def get(
      name : String,
    ) : GoogleLongrunningOperation
      req_path = "v2/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleLongrunningOperation,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.
    def list(
      name : String,
      filter : String? = nil,
      page_size : Int64? = nil,
      page_token : String? = nil,
      return_partial_success : Bool? = nil,
    ) : GoogleLongrunningListOperationsResponse
      req_path = "v2/{+name}/operations"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["filter"] = filter unless filter.nil?
      params["pageSize"] = page_size unless page_size.nil?
      params["pageToken"] = page_token unless page_token.nil?
      params["returnPartialSuccess"] = return_partial_success unless return_partial_success.nil?

      @client.execute(
        type: GoogleLongrunningListOperationsResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.
    def delete(
      name : String,
    ) : GoogleProtobufEmpty
      req_path = "v2/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleProtobufEmpty,
        http_method: "DELETE",
        path: req_path,
        params: params,
        body: nil
      )
    end
  end
end
