# Generated by Google APIs Discovery Generator for run (v2)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Run::V2
  class ProjectsLocationsJobsExecutionsService < GoogleApis::Service
    # Read the status of an image export operation.
    def export_status(
      name : String,
      operation_id : String,
    ) : GoogleCloudRunV2ExportStatusResponse
      req_path = "v2/{+name}/{+operationId}:exportStatus"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{operationId}", URI.encode_path_segment(operation_id.to_s))
      req_path = req_path.gsub("{+operationId}", operation_id.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleCloudRunV2ExportStatusResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Deletes an Execution.
    def delete(
      name : String,
      etag : String? = nil,
      validate_only : Bool? = nil,
    ) : GoogleLongrunningOperation
      req_path = "v2/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["etag"] = etag unless etag.nil?
      params["validateOnly"] = validate_only unless validate_only.nil?

      @client.execute(
        type: GoogleLongrunningOperation,
        http_method: "DELETE",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Gets information about an Execution.
    def get(
      name : String,
    ) : GoogleCloudRunV2Execution
      req_path = "v2/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleCloudRunV2Execution,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Lists Executions from a Job. Results are sorted by creation time, descending.
    def list(
      parent : String,
      page_size : Int64? = nil,
      page_token : String? = nil,
      show_deleted : Bool? = nil,
    ) : GoogleCloudRunV2ListExecutionsResponse
      req_path = "v2/{+parent}/executions"
      req_path = req_path.gsub("{parent}", URI.encode_path_segment(parent.to_s))
      req_path = req_path.gsub("{+parent}", parent.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["pageSize"] = page_size unless page_size.nil?
      params["pageToken"] = page_token unless page_token.nil?
      params["showDeleted"] = show_deleted unless show_deleted.nil?

      @client.execute(
        type: GoogleCloudRunV2ListExecutionsResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Cancels an Execution.
    def cancel(
      name : String,
      body : GoogleCloudRunV2CancelExecutionRequest? = nil,
    ) : GoogleLongrunningOperation
      req_path = "v2/{+name}:cancel"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleLongrunningOperation,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end
  end
end
