# Generated by Google APIs Discovery Generator for run (v2)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Run::V2
  class ProjectsLocationsJobsService < GoogleApis::Service
    # Lists Jobs. Results are sorted by creation time, descending.
    def list(
      parent : String,
      page_size : Int64? = nil,
      page_token : String? = nil,
      show_deleted : Bool? = nil,
    ) : GoogleCloudRunV2ListJobsResponse
      req_path = "v2/{+parent}/jobs"
      req_path = req_path.gsub("{parent}", URI.encode_path_segment(parent.to_s))
      req_path = req_path.gsub("{+parent}", parent.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["pageSize"] = page_size unless page_size.nil?
      params["pageToken"] = page_token unless page_token.nil?
      params["showDeleted"] = show_deleted unless show_deleted.nil?

      @client.execute(
        type: GoogleCloudRunV2ListJobsResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Triggers creation of a new Execution of this Job.
    def run(
      name : String,
      body : GoogleCloudRunV2RunJobRequest? = nil,
    ) : GoogleLongrunningOperation
      req_path = "v2/{+name}:run"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleLongrunningOperation,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Returns permissions that a caller has on the specified Project. There are no permissions required for making this API call.
    def test_iam_permissions(
      resource : String,
      body : GoogleIamV1TestIamPermissionsRequest? = nil,
    ) : GoogleIamV1TestIamPermissionsResponse
      req_path = "v2/{+resource}:testIamPermissions"
      req_path = req_path.gsub("{resource}", URI.encode_path_segment(resource.to_s))
      req_path = req_path.gsub("{+resource}", resource.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleIamV1TestIamPermissionsResponse,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Gets information about a Job.
    def get(
      name : String,
    ) : GoogleCloudRunV2Job
      req_path = "v2/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleCloudRunV2Job,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Sets the IAM Access control policy for the specified Job. Overwrites any existing policy.
    def set_iam_policy(
      resource : String,
      body : GoogleIamV1SetIamPolicyRequest? = nil,
    ) : GoogleIamV1Policy
      req_path = "v2/{+resource}:setIamPolicy"
      req_path = req_path.gsub("{resource}", URI.encode_path_segment(resource.to_s))
      req_path = req_path.gsub("{+resource}", resource.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleIamV1Policy,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Deletes a Job.
    def delete(
      name : String,
      etag : String? = nil,
      validate_only : Bool? = nil,
    ) : GoogleLongrunningOperation
      req_path = "v2/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["etag"] = etag unless etag.nil?
      params["validateOnly"] = validate_only unless validate_only.nil?

      @client.execute(
        type: GoogleLongrunningOperation,
        http_method: "DELETE",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Gets the IAM Access Control policy currently in effect for the given Job. This result does not include any inherited policies.
    def get_iam_policy(
      resource : String,
      options_requested_policy_version : Int64? = nil,
    ) : GoogleIamV1Policy
      req_path = "v2/{+resource}:getIamPolicy"
      req_path = req_path.gsub("{resource}", URI.encode_path_segment(resource.to_s))
      req_path = req_path.gsub("{+resource}", resource.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["options.requestedPolicyVersion"] = options_requested_policy_version unless options_requested_policy_version.nil?

      @client.execute(
        type: GoogleIamV1Policy,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Updates a Job.
    def patch(
      name : String,
      body : GoogleCloudRunV2Job? = nil,
      allow_missing : Bool? = nil,
      validate_only : Bool? = nil,
    ) : GoogleLongrunningOperation
      req_path = "v2/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["allowMissing"] = allow_missing unless allow_missing.nil?
      params["validateOnly"] = validate_only unless validate_only.nil?

      @client.execute(
        type: GoogleLongrunningOperation,
        http_method: "PATCH",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Creates a Job.
    def create(
      parent : String,
      body : GoogleCloudRunV2Job? = nil,
      job_id : String? = nil,
      validate_only : Bool? = nil,
    ) : GoogleLongrunningOperation
      req_path = "v2/{+parent}/jobs"
      req_path = req_path.gsub("{parent}", URI.encode_path_segment(parent.to_s))
      req_path = req_path.gsub("{+parent}", parent.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["jobId"] = job_id unless job_id.nil?
      params["validateOnly"] = validate_only unless validate_only.nil?

      @client.execute(
        type: GoogleLongrunningOperation,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end
  end
end
