# Generated by Google APIs Discovery Generator for run (v2)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Run::V2
  class ProjectsLocationsJobsExecutionsTasksService < GoogleApis::Service
    # Gets information about a Task.
    def get(
      name : String,
    ) : GoogleCloudRunV2Task
      req_path = "v2/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleCloudRunV2Task,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Lists Tasks from an Execution of a Job.
    def list(
      parent : String,
      page_size : Int64? = nil,
      page_token : String? = nil,
      show_deleted : Bool? = nil,
    ) : GoogleCloudRunV2ListTasksResponse
      req_path = "v2/{+parent}/tasks"
      req_path = req_path.gsub("{parent}", URI.encode_path_segment(parent.to_s))
      req_path = req_path.gsub("{+parent}", parent.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["pageSize"] = page_size unless page_size.nil?
      params["pageToken"] = page_token unless page_token.nil?
      params["showDeleted"] = show_deleted unless show_deleted.nil?

      @client.execute(
        type: GoogleCloudRunV2ListTasksResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end
  end
end
