# Generated by Google APIs Discovery Generator for run (v2)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Run::V2
  class ProjectsLocationsService < GoogleApis::Service
    # Export image metadata for a given resource.
    def export_image_metadata(
      name : String,
    ) : GoogleCloudRunV2Metadata
      req_path = "v2/{+name}:exportImageMetadata"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleCloudRunV2Metadata,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Export generated customer metadata for a given resource.
    def export_metadata(
      name : String,
    ) : GoogleCloudRunV2Metadata
      req_path = "v2/{+name}:exportMetadata"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleCloudRunV2Metadata,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Export image for a given resource.
    def export_image(
      name : String,
      body : GoogleCloudRunV2ExportImageRequest? = nil,
    ) : GoogleCloudRunV2ExportImageResponse
      req_path = "v2/{+name}:exportImage"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleCloudRunV2ExportImageResponse,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Export generated customer metadata for a given project.
    def export_project_metadata(
      name : String,
    ) : GoogleCloudRunV2Metadata
      req_path = "v2/{+name}:exportProjectMetadata"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleCloudRunV2Metadata,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end
  end
end
