# Generated by Google APIs Discovery Generator for run (v2)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Run::V2
  class ProjectsLocationsBuildsService < GoogleApis::Service
    # Submits a build in a given project.
    def submit(
      parent : String,
      body : GoogleCloudRunV2SubmitBuildRequest? = nil,
    ) : GoogleCloudRunV2SubmitBuildResponse
      req_path = "v2/{+parent}/builds:submit"
      req_path = req_path.gsub("{parent}", URI.encode_path_segment(parent.to_s))
      req_path = req_path.gsub("{+parent}", parent.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleCloudRunV2SubmitBuildResponse,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end
  end
end
