# Generated by Google APIs Discovery Generator for artifactregistry (v1)
# Do not edit directly.

require "../../client"
require "../../auth"
require "./projects_service"
require "./projects_locations_service"
require "./projects_locations_operations_service"
require "./projects_locations_repositories_service"
require "./projects_locations_repositories_packages_service"
require "./projects_locations_repositories_packages_versions_service"
require "./projects_locations_repositories_packages_tags_service"
require "./projects_locations_repositories_generic_artifacts_service"
require "./projects_locations_repositories_attachments_service"
require "./projects_locations_repositories_apt_artifacts_service"
require "./projects_locations_repositories_docker_images_service"
require "./projects_locations_repositories_rules_service"
require "./projects_locations_repositories_prewarmed_artifacts_service"
require "./projects_locations_repositories_googet_artifacts_service"
require "./projects_locations_repositories_kfp_artifacts_service"
require "./projects_locations_repositories_files_service"
require "./projects_locations_repositories_go_modules_service"
require "./projects_locations_repositories_python_packages_service"
require "./projects_locations_repositories_npm_packages_service"
require "./projects_locations_repositories_maven_artifacts_service"
require "./projects_locations_repositories_yum_artifacts_service"

module GoogleApis::Artifactregistry::V1
  # Client for the Artifact Registry API API (v1).
  class Client
    DEFAULT_BASE_URL = "https://artifactregistry.googleapis.com/"

    getter client : GoogleApis::Client
    getter projects : ProjectsService
    getter projects_locations : ProjectsLocationsService
    getter projects_locations_operations : ProjectsLocationsOperationsService
    getter projects_locations_repositories : ProjectsLocationsRepositoriesService
    getter projects_locations_repositories_packages : ProjectsLocationsRepositoriesPackagesService
    getter projects_locations_repositories_packages_versions : ProjectsLocationsRepositoriesPackagesVersionsService
    getter projects_locations_repositories_packages_tags : ProjectsLocationsRepositoriesPackagesTagsService
    getter projects_locations_repositories_generic_artifacts : ProjectsLocationsRepositoriesGenericArtifactsService
    getter projects_locations_repositories_attachments : ProjectsLocationsRepositoriesAttachmentsService
    getter projects_locations_repositories_apt_artifacts : ProjectsLocationsRepositoriesAptArtifactsService
    getter projects_locations_repositories_docker_images : ProjectsLocationsRepositoriesDockerImagesService
    getter projects_locations_repositories_rules : ProjectsLocationsRepositoriesRulesService
    getter projects_locations_repositories_prewarmed_artifacts : ProjectsLocationsRepositoriesPrewarmedArtifactsService
    getter projects_locations_repositories_googet_artifacts : ProjectsLocationsRepositoriesGoogetArtifactsService
    getter projects_locations_repositories_kfp_artifacts : ProjectsLocationsRepositoriesKfpArtifactsService
    getter projects_locations_repositories_files : ProjectsLocationsRepositoriesFilesService
    getter projects_locations_repositories_go_modules : ProjectsLocationsRepositoriesGoModulesService
    getter projects_locations_repositories_python_packages : ProjectsLocationsRepositoriesPythonPackagesService
    getter projects_locations_repositories_npm_packages : ProjectsLocationsRepositoriesNpmPackagesService
    getter projects_locations_repositories_maven_artifacts : ProjectsLocationsRepositoriesMavenArtifactsService
    getter projects_locations_repositories_yum_artifacts : ProjectsLocationsRepositoriesYumArtifactsService

    def initialize(
      credentials : GoogleApis::Auth::Credentials,
      base_url : String = DEFAULT_BASE_URL,
    )
      @client = GoogleApis::Client.new(credentials, base_url)
      @projects = ProjectsService.new(@client)
      @projects_locations = ProjectsLocationsService.new(@client)
      @projects_locations_operations = ProjectsLocationsOperationsService.new(@client)
      @projects_locations_repositories = ProjectsLocationsRepositoriesService.new(@client)
      @projects_locations_repositories_packages = ProjectsLocationsRepositoriesPackagesService.new(@client)
      @projects_locations_repositories_packages_versions = ProjectsLocationsRepositoriesPackagesVersionsService.new(@client)
      @projects_locations_repositories_packages_tags = ProjectsLocationsRepositoriesPackagesTagsService.new(@client)
      @projects_locations_repositories_generic_artifacts = ProjectsLocationsRepositoriesGenericArtifactsService.new(@client)
      @projects_locations_repositories_attachments = ProjectsLocationsRepositoriesAttachmentsService.new(@client)
      @projects_locations_repositories_apt_artifacts = ProjectsLocationsRepositoriesAptArtifactsService.new(@client)
      @projects_locations_repositories_docker_images = ProjectsLocationsRepositoriesDockerImagesService.new(@client)
      @projects_locations_repositories_rules = ProjectsLocationsRepositoriesRulesService.new(@client)
      @projects_locations_repositories_prewarmed_artifacts = ProjectsLocationsRepositoriesPrewarmedArtifactsService.new(@client)
      @projects_locations_repositories_googet_artifacts = ProjectsLocationsRepositoriesGoogetArtifactsService.new(@client)
      @projects_locations_repositories_kfp_artifacts = ProjectsLocationsRepositoriesKfpArtifactsService.new(@client)
      @projects_locations_repositories_files = ProjectsLocationsRepositoriesFilesService.new(@client)
      @projects_locations_repositories_go_modules = ProjectsLocationsRepositoriesGoModulesService.new(@client)
      @projects_locations_repositories_python_packages = ProjectsLocationsRepositoriesPythonPackagesService.new(@client)
      @projects_locations_repositories_npm_packages = ProjectsLocationsRepositoriesNpmPackagesService.new(@client)
      @projects_locations_repositories_maven_artifacts = ProjectsLocationsRepositoriesMavenArtifactsService.new(@client)
      @projects_locations_repositories_yum_artifacts = ProjectsLocationsRepositoriesYumArtifactsService.new(@client)
    end
  end
end
