# Generated by Google APIs Discovery Generator for artifactregistry (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Artifactregistry::V1
  class ProjectsLocationsRepositoriesFilesService < GoogleApis::Service
    # Download a file.
    def download(
      name : String,
    ) : DownloadFileResponse
      req_path = "v1/{+name}:download"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: DownloadFileResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Updates a file.
    def patch(
      name : String,
      body : GoogleDevtoolsArtifactregistryV1File? = nil,
      update_mask : String? = nil,
    ) : GoogleDevtoolsArtifactregistryV1File
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["updateMask"] = update_mask unless update_mask.nil?

      @client.execute(
        type: GoogleDevtoolsArtifactregistryV1File,
        http_method: "PATCH",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Gets a file.
    def get(
      name : String,
    ) : GoogleDevtoolsArtifactregistryV1File
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleDevtoolsArtifactregistryV1File,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Deletes a file and all of its content. It is only allowed on generic repositories. The returned operation will complete once the file has been deleted.
    def delete(
      name : String,
    ) : Operation
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: Operation,
        http_method: "DELETE",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Lists files.
    def list(
      parent : String,
      filter : String? = nil,
      order_by : String? = nil,
      page_size : Int64? = nil,
      page_token : String? = nil,
    ) : ListFilesResponse
      req_path = "v1/{+parent}/files"
      req_path = req_path.gsub("{parent}", URI.encode_path_segment(parent.to_s))
      req_path = req_path.gsub("{+parent}", parent.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["filter"] = filter unless filter.nil?
      params["orderBy"] = order_by unless order_by.nil?
      params["pageSize"] = page_size unless page_size.nil?
      params["pageToken"] = page_token unless page_token.nil?

      @client.execute(
        type: ListFilesResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Directly uploads a file to a repository. The returned Operation will complete once the resources are uploaded.
    def upload(
      parent : String,
      body : UploadFileRequest? = nil,
    ) : UploadFileMediaResponse
      req_path = "v1/{+parent}/files:upload"
      req_path = req_path.gsub("{parent}", URI.encode_path_segment(parent.to_s))
      req_path = req_path.gsub("{+parent}", parent.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: UploadFileMediaResponse,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end
  end
end
