# Generated by Google APIs Discovery Generator for artifactregistry (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Artifactregistry::V1
  class ProjectsLocationsRepositoriesPackagesVersionsService < GoogleApis::Service
    # Deletes multiple versions across a repository. The returned operation will complete once the versions have been deleted.
    def batch_delete(
      parent : String,
      body : BatchDeleteVersionsRequest? = nil,
    ) : Operation
      req_path = "v1/{+parent}/versions:batchDelete"
      req_path = req_path.gsub("{parent}", URI.encode_path_segment(parent.to_s))
      req_path = req_path.gsub("{+parent}", parent.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: Operation,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Deletes a version and all of its content. The returned operation will complete once the version has been deleted.
    def delete(
      name : String,
      force : Bool? = nil,
    ) : Operation
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["force"] = force unless force.nil?

      @client.execute(
        type: Operation,
        http_method: "DELETE",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Lists versions.
    def list(
      parent : String,
      filter : String? = nil,
      order_by : String? = nil,
      page_size : Int64? = nil,
      page_token : String? = nil,
      view : String? = nil,
    ) : ListVersionsResponse
      req_path = "v1/{+parent}/versions"
      req_path = req_path.gsub("{parent}", URI.encode_path_segment(parent.to_s))
      req_path = req_path.gsub("{+parent}", parent.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["filter"] = filter unless filter.nil?
      params["orderBy"] = order_by unless order_by.nil?
      params["pageSize"] = page_size unless page_size.nil?
      params["pageToken"] = page_token unless page_token.nil?
      params["view"] = view unless view.nil?

      @client.execute(
        type: ListVersionsResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Updates a version.
    def patch(
      name : String,
      body : Version? = nil,
      update_mask : String? = nil,
    ) : Version
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["updateMask"] = update_mask unless update_mask.nil?

      @client.execute(
        type: Version,
        http_method: "PATCH",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Gets a version
    def get(
      name : String,
      view : String? = nil,
    ) : Version
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["view"] = view unless view.nil?

      @client.execute(
        type: Version,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end
  end
end
