# Generated by Google APIs Discovery Generator for artifactregistry (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Artifactregistry::V1
  class ProjectsLocationsRepositoriesRulesService < GoogleApis::Service
    # Updates a rule.
    def patch(
      name : String,
      body : GoogleDevtoolsArtifactregistryV1Rule? = nil,
      update_mask : String? = nil,
    ) : GoogleDevtoolsArtifactregistryV1Rule
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["updateMask"] = update_mask unless update_mask.nil?

      @client.execute(
        type: GoogleDevtoolsArtifactregistryV1Rule,
        http_method: "PATCH",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Gets a rule.
    def get(
      name : String,
    ) : GoogleDevtoolsArtifactregistryV1Rule
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleDevtoolsArtifactregistryV1Rule,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Deletes a rule.
    def delete(
      name : String,
    ) : Empty
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: Empty,
        http_method: "DELETE",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Creates a rule.
    def create(
      parent : String,
      body : GoogleDevtoolsArtifactregistryV1Rule? = nil,
      rule_id : String? = nil,
    ) : GoogleDevtoolsArtifactregistryV1Rule
      req_path = "v1/{+parent}/rules"
      req_path = req_path.gsub("{parent}", URI.encode_path_segment(parent.to_s))
      req_path = req_path.gsub("{+parent}", parent.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["ruleId"] = rule_id unless rule_id.nil?

      @client.execute(
        type: GoogleDevtoolsArtifactregistryV1Rule,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Lists rules.
    def list(
      parent : String,
      page_size : Int64? = nil,
      page_token : String? = nil,
    ) : ListRulesResponse
      req_path = "v1/{+parent}/rules"
      req_path = req_path.gsub("{parent}", URI.encode_path_segment(parent.to_s))
      req_path = req_path.gsub("{+parent}", parent.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["pageSize"] = page_size unless page_size.nil?
      params["pageToken"] = page_token unless page_token.nil?

      @client.execute(
        type: ListRulesResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end
  end
end
