# Generated by Google APIs Discovery Generator for artifactregistry (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Artifactregistry::V1
  class ProjectsLocationsRepositoriesPrewarmedArtifactsService < GoogleApis::Service
    # Lists all streamed artifacts in a repository.
    def list(
      parent : String,
      filter : String? = nil,
      page_size : Int64? = nil,
      page_token : String? = nil,
    ) : ListPrewarmedArtifactsResponse
      req_path = "v1/{+parent}/prewarmedArtifacts"
      req_path = req_path.gsub("{parent}", URI.encode_path_segment(parent.to_s))
      req_path = req_path.gsub("{+parent}", parent.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["filter"] = filter unless filter.nil?
      params["pageSize"] = page_size unless page_size.nil?
      params["pageToken"] = page_token unless page_token.nil?

      @client.execute(
        type: ListPrewarmedArtifactsResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end
  end
end
