# Generated by Google APIs Discovery Generator for artifactregistry (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Artifactregistry::V1
  class ProjectsLocationsRepositoriesPackagesService < GoogleApis::Service
    # Updates a package.
    def patch(
      name : String,
      body : Package? = nil,
      update_mask : String? = nil,
    ) : Package
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["updateMask"] = update_mask unless update_mask.nil?

      @client.execute(
        type: Package,
        http_method: "PATCH",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Lists packages.
    def list(
      parent : String,
      filter : String? = nil,
      order_by : String? = nil,
      page_size : Int64? = nil,
      page_token : String? = nil,
    ) : ListPackagesResponse
      req_path = "v1/{+parent}/packages"
      req_path = req_path.gsub("{parent}", URI.encode_path_segment(parent.to_s))
      req_path = req_path.gsub("{+parent}", parent.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["filter"] = filter unless filter.nil?
      params["orderBy"] = order_by unless order_by.nil?
      params["pageSize"] = page_size unless page_size.nil?
      params["pageToken"] = page_token unless page_token.nil?

      @client.execute(
        type: ListPackagesResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Gets a package.
    def get(
      name : String,
    ) : Package
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: Package,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Deletes a package and all of its versions and tags. The returned operation will complete once the package has been deleted.
    def delete(
      name : String,
    ) : Operation
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: Operation,
        http_method: "DELETE",
        path: req_path,
        params: params,
        body: nil
      )
    end
  end
end
