# Generated by Google APIs Discovery Generator for artifactregistry (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Artifactregistry::V1
  class ProjectsLocationsRepositoriesAttachmentsService < GoogleApis::Service
    # Creates an attachment. The returned Operation will finish once the attachment has been created. Its response will be the created attachment.
    def create(
      parent : String,
      body : Attachment? = nil,
      attachment_id : String? = nil,
    ) : Operation
      req_path = "v1/{+parent}/attachments"
      req_path = req_path.gsub("{parent}", URI.encode_path_segment(parent.to_s))
      req_path = req_path.gsub("{+parent}", parent.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["attachmentId"] = attachment_id unless attachment_id.nil?

      @client.execute(
        type: Operation,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Gets an attachment.
    def get(
      name : String,
    ) : Attachment
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: Attachment,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Deletes an attachment. The returned Operation will finish once the attachments has been deleted. It will not have any Operation metadata and will return a `google.protobuf.Empty` response.
    def delete(
      name : String,
    ) : Operation
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: Operation,
        http_method: "DELETE",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Lists attachments.
    def list(
      parent : String,
      filter : String? = nil,
      page_size : Int64? = nil,
      page_token : String? = nil,
    ) : ListAttachmentsResponse
      req_path = "v1/{+parent}/attachments"
      req_path = req_path.gsub("{parent}", URI.encode_path_segment(parent.to_s))
      req_path = req_path.gsub("{+parent}", parent.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["filter"] = filter unless filter.nil?
      params["pageSize"] = page_size unless page_size.nil?
      params["pageToken"] = page_token unless page_token.nil?

      @client.execute(
        type: ListAttachmentsResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end
  end
end
