# Generated by Google APIs Discovery Generator for artifactregistry (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Artifactregistry::V1
  class ProjectsLocationsRepositoriesMavenArtifactsService < GoogleApis::Service
    # Lists maven artifacts.
    def list(
      parent : String,
      page_size : Int64? = nil,
      page_token : String? = nil,
    ) : ListMavenArtifactsResponse
      req_path = "v1/{+parent}/mavenArtifacts"
      req_path = req_path.gsub("{parent}", URI.encode_path_segment(parent.to_s))
      req_path = req_path.gsub("{+parent}", parent.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["pageSize"] = page_size unless page_size.nil?
      params["pageToken"] = page_token unless page_token.nil?

      @client.execute(
        type: ListMavenArtifactsResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Gets a maven artifact.
    def get(
      name : String,
    ) : MavenArtifact
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: MavenArtifact,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end
  end
end
