# Generated by Google APIs Discovery Generator for artifactregistry (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Artifactregistry::V1
  class ProjectsService < GoogleApis::Service
    # Updates the Settings for the Project.
    def update_project_settings(
      name : String,
      body : ProjectSettings? = nil,
      update_mask : String? = nil,
    ) : ProjectSettings
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["updateMask"] = update_mask unless update_mask.nil?

      @client.execute(
        type: ProjectSettings,
        http_method: "PATCH",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Retrieves the Settings for the Project.
    def get_project_settings(
      name : String,
    ) : ProjectSettings
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: ProjectSettings,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end
  end
end
