# Generated by Google APIs Discovery Generator for artifactregistry (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Artifactregistry::V1
  class ProjectsLocationsService < GoogleApis::Service
    # Updates the project configuration.
    def update_project_config(
      name : String,
      body : ProjectConfig? = nil,
      update_mask : String? = nil,
    ) : ProjectConfig
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["updateMask"] = update_mask unless update_mask.nil?

      @client.execute(
        type: ProjectConfig,
        http_method: "PATCH",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Updates the VPCSC Config for the Project.
    def update_vpcsc_config(
      name : String,
      body : VPCSCConfig? = nil,
      update_mask : String? = nil,
    ) : VPCSCConfig
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["updateMask"] = update_mask unless update_mask.nil?

      @client.execute(
        type: VPCSCConfig,
        http_method: "PATCH",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Gets information about a location.
    def get(
      name : String,
    ) : Location
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: Location,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Retrieves the VPCSC Config for the Project.
    def get_vpcsc_config(
      name : String,
    ) : VPCSCConfig
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: VPCSCConfig,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Retrieves the project configuration.
    def get_project_config(
      name : String,
    ) : ProjectConfig
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: ProjectConfig,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Lists information about the supported locations for this service. This method lists locations based on the resource scope provided in the ListLocationsRequest.name field: * **Global locations**: If `name` is empty, the method lists the public locations available to all projects. * **Project-specific locations**: If `name` follows the format `projects/{project}`, the method lists locations visible to that specific project. This includes public, private, or other project-specific locations enabled for the project. For gRPC and client library implementations, the resource name is passed as the `name` field. For direct service calls, the resource name is incorporated into the request path based on the specific service implementation and version.
    def list(
      name : String,
      extra_location_types : String? = nil,
      filter : String? = nil,
      page_size : Int64? = nil,
      page_token : String? = nil,
    ) : ListLocationsResponse
      req_path = "v1/{+name}/locations"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["extraLocationTypes"] = extra_location_types unless extra_location_types.nil?
      params["filter"] = filter unless filter.nil?
      params["pageSize"] = page_size unless page_size.nil?
      params["pageToken"] = page_token unless page_token.nil?

      @client.execute(
        type: ListLocationsResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end
  end
end
