# Generated by Google APIs Discovery Generator for artifactregistry (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Artifactregistry::V1
  class ProjectsLocationsRepositoriesPackagesTagsService < GoogleApis::Service
    # Lists tags.
    def list(
      parent : String,
      filter : String? = nil,
      page_size : Int64? = nil,
      page_token : String? = nil,
    ) : ListTagsResponse
      req_path = "v1/{+parent}/tags"
      req_path = req_path.gsub("{parent}", URI.encode_path_segment(parent.to_s))
      req_path = req_path.gsub("{+parent}", parent.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["filter"] = filter unless filter.nil?
      params["pageSize"] = page_size unless page_size.nil?
      params["pageToken"] = page_token unless page_token.nil?

      @client.execute(
        type: ListTagsResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Gets a tag.
    def get(
      name : String,
    ) : Tag
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: Tag,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Updates a tag.
    def patch(
      name : String,
      body : Tag? = nil,
      update_mask : String? = nil,
    ) : Tag
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["updateMask"] = update_mask unless update_mask.nil?

      @client.execute(
        type: Tag,
        http_method: "PATCH",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Creates a tag.
    def create(
      parent : String,
      body : Tag? = nil,
      tag_id : String? = nil,
    ) : Tag
      req_path = "v1/{+parent}/tags"
      req_path = req_path.gsub("{parent}", URI.encode_path_segment(parent.to_s))
      req_path = req_path.gsub("{+parent}", parent.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["tagId"] = tag_id unless tag_id.nil?

      @client.execute(
        type: Tag,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Deletes a tag.
    def delete(
      name : String,
    ) : Empty
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: Empty,
        http_method: "DELETE",
        path: req_path,
        params: params,
        body: nil
      )
    end
  end
end
