# Generated by Google APIs Discovery Generator for artifactregistry (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Artifactregistry::V1
  class ProjectsLocationsRepositoriesGoModulesService < GoogleApis::Service
    # Directly uploads a Go module. The returned Operation will complete once the Go module is uploaded. Package, Version, and File resources are created based on the uploaded Go module.
    def upload(
      parent : String,
      body : UploadGoModuleRequest? = nil,
    ) : UploadGoModuleMediaResponse
      req_path = "v1/{+parent}/goModules:create"
      req_path = req_path.gsub("{parent}", URI.encode_path_segment(parent.to_s))
      req_path = req_path.gsub("{+parent}", parent.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: UploadGoModuleMediaResponse,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end
  end
end
