# Generated by Google APIs Discovery Generator for artifactregistry (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Artifactregistry::V1
  class ProjectsLocationsRepositoriesService < GoogleApis::Service
    # Exports an artifact to a Cloud Storage bucket.
    def export_artifact(
      repository : String,
      body : ExportArtifactRequest? = nil,
    ) : Operation
      req_path = "v1/{+repository}:exportArtifact"
      req_path = req_path.gsub("{repository}", URI.encode_path_segment(repository.to_s))
      req_path = req_path.gsub("{+repository}", repository.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: Operation,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Prewarms an artifact for streaming.
    def prewarm_artifact(
      repository : String,
      body : PrewarmArtifactRequest? = nil,
    ) : Operation
      req_path = "v1/{+repository}:prewarmArtifact"
      req_path = req_path.gsub("{repository}", URI.encode_path_segment(repository.to_s))
      req_path = req_path.gsub("{+repository}", repository.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: Operation,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Deletes a repository and all of its contents. The returned Operation will finish once the repository has been deleted. It will not have any Operation metadata and will return a google.protobuf.Empty response.
    def delete(
      name : String,
    ) : Operation
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: Operation,
        http_method: "DELETE",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Updates the IAM policy for a given resource.
    def set_iam_policy(
      resource : String,
      body : SetIamPolicyRequest? = nil,
    ) : Policy
      req_path = "v1/{+resource}:setIamPolicy"
      req_path = req_path.gsub("{resource}", URI.encode_path_segment(resource.to_s))
      req_path = req_path.gsub("{+resource}", resource.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: Policy,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Tests if the caller has a list of permissions on a resource.
    def test_iam_permissions(
      resource : String,
      body : TestIamPermissionsRequest? = nil,
    ) : TestIamPermissionsResponse
      req_path = "v1/{+resource}:testIamPermissions"
      req_path = req_path.gsub("{resource}", URI.encode_path_segment(resource.to_s))
      req_path = req_path.gsub("{+resource}", resource.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: TestIamPermissionsResponse,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Creates a repository. The returned Operation will finish once the repository has been created. Its response will be the created Repository.
    def create(
      parent : String,
      body : Repository? = nil,
      repository_id : String? = nil,
    ) : Operation
      req_path = "v1/{+parent}/repositories"
      req_path = req_path.gsub("{parent}", URI.encode_path_segment(parent.to_s))
      req_path = req_path.gsub("{+parent}", parent.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["repositoryId"] = repository_id unless repository_id.nil?

      @client.execute(
        type: Operation,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Gets a repository.
    def get(
      name : String,
    ) : Repository
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: Repository,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Removes an artifact from streaming.
    def remove_prewarmed_artifact(
      repository : String,
      body : RemovePrewarmedArtifactRequest? = nil,
    ) : RemovePrewarmedArtifactResponse
      req_path = "v1/{+repository}:removePrewarmedArtifact"
      req_path = req_path.gsub("{repository}", URI.encode_path_segment(repository.to_s))
      req_path = req_path.gsub("{+repository}", repository.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: RemovePrewarmedArtifactResponse,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Gets the IAM policy for a given resource.
    def get_iam_policy(
      resource : String,
      options_requested_policy_version : Int64? = nil,
    ) : Policy
      req_path = "v1/{+resource}:getIamPolicy"
      req_path = req_path.gsub("{resource}", URI.encode_path_segment(resource.to_s))
      req_path = req_path.gsub("{+resource}", resource.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["options.requestedPolicyVersion"] = options_requested_policy_version unless options_requested_policy_version.nil?

      @client.execute(
        type: Policy,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Lists repositories.
    def list(
      parent : String,
      filter : String? = nil,
      order_by : String? = nil,
      page_size : Int64? = nil,
      page_token : String? = nil,
    ) : ListRepositoriesResponse
      req_path = "v1/{+parent}/repositories"
      req_path = req_path.gsub("{parent}", URI.encode_path_segment(parent.to_s))
      req_path = req_path.gsub("{+parent}", parent.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["filter"] = filter unless filter.nil?
      params["orderBy"] = order_by unless order_by.nil?
      params["pageSize"] = page_size unless page_size.nil?
      params["pageToken"] = page_token unless page_token.nil?

      @client.execute(
        type: ListRepositoriesResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Checks an artifact streaming.
    def check_prewarmed_artifact(
      repository : String,
      body : CheckPrewarmedArtifactRequest? = nil,
    ) : CheckPrewarmedArtifactResponse
      req_path = "v1/{+repository}:checkPrewarmedArtifact"
      req_path = req_path.gsub("{repository}", URI.encode_path_segment(repository.to_s))
      req_path = req_path.gsub("{+repository}", repository.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: CheckPrewarmedArtifactResponse,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Updates a repository.
    def patch(
      name : String,
      body : Repository? = nil,
      update_mask : String? = nil,
    ) : Repository
      req_path = "v1/{+name}"
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["updateMask"] = update_mask unless update_mask.nil?

      @client.execute(
        type: Repository,
        http_method: "PATCH",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end
  end
end
