# Generated by Google APIs Discovery Generator for artifactregistry (v1)
# Do not edit directly.

require "./types"
require "./client"
require "./projects_service"
require "./projects_locations_service"
require "./projects_locations_operations_service"
require "./projects_locations_repositories_service"
require "./projects_locations_repositories_packages_service"
require "./projects_locations_repositories_packages_versions_service"
require "./projects_locations_repositories_packages_tags_service"
require "./projects_locations_repositories_generic_artifacts_service"
require "./projects_locations_repositories_attachments_service"
require "./projects_locations_repositories_apt_artifacts_service"
require "./projects_locations_repositories_docker_images_service"
require "./projects_locations_repositories_rules_service"
require "./projects_locations_repositories_prewarmed_artifacts_service"
require "./projects_locations_repositories_googet_artifacts_service"
require "./projects_locations_repositories_kfp_artifacts_service"
require "./projects_locations_repositories_files_service"
require "./projects_locations_repositories_go_modules_service"
require "./projects_locations_repositories_python_packages_service"
require "./projects_locations_repositories_npm_packages_service"
require "./projects_locations_repositories_maven_artifacts_service"
require "./projects_locations_repositories_yum_artifacts_service"

module GoogleApis::Artifactregistry::V1
end
