# Generated by Google APIs Discovery Generator for storage (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Storage::V1
  class AnywhereCachesService < GoogleApis::Service
    # Creates an Anywhere Cache instance.
    def insert(
      bucket : String,
      body : AnywhereCache? = nil,
    ) : GoogleLongrunningOperation
      req_path = "b/{bucket}/anywhereCaches"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleLongrunningOperation,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Updates the config of an Anywhere Cache instance.
    def update(
      bucket : String,
      anywhere_cache_id : String,
      body : AnywhereCache? = nil,
    ) : GoogleLongrunningOperation
      req_path = "b/{bucket}/anywhereCaches/{anywhereCacheId}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{anywhereCacheId}", URI.encode_path_segment(anywhere_cache_id.to_s))
      req_path = req_path.gsub("{+anywhereCacheId}", anywhere_cache_id.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleLongrunningOperation,
        http_method: "PATCH",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Returns the metadata of an Anywhere Cache instance.
    def get(
      bucket : String,
      anywhere_cache_id : String,
    ) : AnywhereCache
      req_path = "b/{bucket}/anywhereCaches/{anywhereCacheId}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{anywhereCacheId}", URI.encode_path_segment(anywhere_cache_id.to_s))
      req_path = req_path.gsub("{+anywhereCacheId}", anywhere_cache_id.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: AnywhereCache,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Returns a list of Anywhere Cache instances of the bucket matching the criteria.
    def list(
      bucket : String,
      page_size : Int64? = nil,
      page_token : String? = nil,
    ) : AnywhereCaches
      req_path = "b/{bucket}/anywhereCaches"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["pageSize"] = page_size unless page_size.nil?
      params["pageToken"] = page_token unless page_token.nil?

      @client.execute(
        type: AnywhereCaches,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Pauses an Anywhere Cache instance.
    def pause(
      bucket : String,
      anywhere_cache_id : String,
    ) : AnywhereCache
      req_path = "b/{bucket}/anywhereCaches/{anywhereCacheId}/pause"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{anywhereCacheId}", URI.encode_path_segment(anywhere_cache_id.to_s))
      req_path = req_path.gsub("{+anywhereCacheId}", anywhere_cache_id.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: AnywhereCache,
        http_method: "POST",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Resumes a paused or disabled Anywhere Cache instance.
    def resume(
      bucket : String,
      anywhere_cache_id : String,
    ) : AnywhereCache
      req_path = "b/{bucket}/anywhereCaches/{anywhereCacheId}/resume"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{anywhereCacheId}", URI.encode_path_segment(anywhere_cache_id.to_s))
      req_path = req_path.gsub("{+anywhereCacheId}", anywhere_cache_id.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: AnywhereCache,
        http_method: "POST",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Disables an Anywhere Cache instance.
    def disable(
      bucket : String,
      anywhere_cache_id : String,
    ) : AnywhereCache
      req_path = "b/{bucket}/anywhereCaches/{anywhereCacheId}/disable"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{anywhereCacheId}", URI.encode_path_segment(anywhere_cache_id.to_s))
      req_path = req_path.gsub("{+anywhereCacheId}", anywhere_cache_id.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: AnywhereCache,
        http_method: "POST",
        path: req_path,
        params: params,
        body: nil
      )
    end
  end
end
