# Generated by Google APIs Discovery Generator for storage (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Storage::V1
  class BucketAccessControlsService < GoogleApis::Service
    # Permanently deletes the ACL entry for the specified entity on the specified bucket.
    def delete(
      bucket : String,
      entity : String,
      user_project : String? = nil,
    ) : Nil
      req_path = "b/{bucket}/acl/{entity}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{entity}", URI.encode_path_segment(entity.to_s))
      req_path = req_path.gsub("{+entity}", entity.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["userProject"] = user_project unless user_project.nil?

      @client.execute_raw(
        http_method: "DELETE",
        path: req_path,
        params: params,
        body: nil
      )
      nil
    end

    # Returns the ACL entry for the specified entity on the specified bucket.
    def get(
      bucket : String,
      entity : String,
      user_project : String? = nil,
    ) : BucketAccessControl
      req_path = "b/{bucket}/acl/{entity}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{entity}", URI.encode_path_segment(entity.to_s))
      req_path = req_path.gsub("{+entity}", entity.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: BucketAccessControl,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Creates a new ACL entry on the specified bucket.
    def insert(
      bucket : String,
      body : BucketAccessControl? = nil,
      user_project : String? = nil,
    ) : BucketAccessControl
      req_path = "b/{bucket}/acl"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: BucketAccessControl,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Retrieves ACL entries on the specified bucket.
    def list(
      bucket : String,
      user_project : String? = nil,
    ) : BucketAccessControls
      req_path = "b/{bucket}/acl"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: BucketAccessControls,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Patches an ACL entry on the specified bucket.
    def patch(
      bucket : String,
      entity : String,
      body : BucketAccessControl? = nil,
      user_project : String? = nil,
    ) : BucketAccessControl
      req_path = "b/{bucket}/acl/{entity}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{entity}", URI.encode_path_segment(entity.to_s))
      req_path = req_path.gsub("{+entity}", entity.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: BucketAccessControl,
        http_method: "PATCH",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Updates an ACL entry on the specified bucket.
    def update(
      bucket : String,
      entity : String,
      body : BucketAccessControl? = nil,
      user_project : String? = nil,
    ) : BucketAccessControl
      req_path = "b/{bucket}/acl/{entity}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{entity}", URI.encode_path_segment(entity.to_s))
      req_path = req_path.gsub("{+entity}", entity.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: BucketAccessControl,
        http_method: "PUT",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end
  end
end
