# Generated by Google APIs Discovery Generator for storage (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Storage::V1
  class BucketsService < GoogleApis::Service
    # Deletes an empty bucket. Deletions are permanent unless soft delete is enabled on the bucket.
    def delete(
      bucket : String,
      if_metageneration_match : String? = nil,
      if_metageneration_not_match : String? = nil,
      user_project : String? = nil,
    ) : Nil
      req_path = "b/{bucket}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["ifMetagenerationMatch"] = if_metageneration_match unless if_metageneration_match.nil?
      params["ifMetagenerationNotMatch"] = if_metageneration_not_match unless if_metageneration_not_match.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute_raw(
        http_method: "DELETE",
        path: req_path,
        params: params,
        body: nil
      )
      nil
    end

    # Restores a soft-deleted bucket.
    def restore(
      bucket : String,
      generation : String,
      projection : String? = nil,
      user_project : String? = nil,
    ) : Bucket
      req_path = "b/{bucket}/restore"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["generation"] = generation
      params["projection"] = projection unless projection.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: Bucket,
        http_method: "POST",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Initiates a long-running Relocate Bucket operation on the specified bucket.
    def relocate(
      bucket : String,
      body : RelocateBucketRequest? = nil,
    ) : GoogleLongrunningOperation
      req_path = "b/{bucket}/relocate"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleLongrunningOperation,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Returns metadata for the specified bucket.
    def get(
      bucket : String,
      generation : String? = nil,
      if_metageneration_match : String? = nil,
      if_metageneration_not_match : String? = nil,
      projection : String? = nil,
      soft_deleted : Bool? = nil,
      user_project : String? = nil,
    ) : Bucket
      req_path = "b/{bucket}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["generation"] = generation unless generation.nil?
      params["ifMetagenerationMatch"] = if_metageneration_match unless if_metageneration_match.nil?
      params["ifMetagenerationNotMatch"] = if_metageneration_not_match unless if_metageneration_not_match.nil?
      params["projection"] = projection unless projection.nil?
      params["softDeleted"] = soft_deleted unless soft_deleted.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: Bucket,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Returns an IAM policy for the specified bucket.
    def get_iam_policy(
      bucket : String,
      options_requested_policy_version : Int64? = nil,
      user_project : String? = nil,
    ) : Policy
      req_path = "b/{bucket}/iam"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["optionsRequestedPolicyVersion"] = options_requested_policy_version unless options_requested_policy_version.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: Policy,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Returns the storage layout configuration for the specified bucket. Note that this operation requires storage.objects.list permission.
    def get_storage_layout(
      bucket : String,
      prefix : String? = nil,
    ) : BucketStorageLayout
      req_path = "b/{bucket}/storageLayout"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["prefix"] = prefix unless prefix.nil?

      @client.execute(
        type: BucketStorageLayout,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Creates a new bucket.
    def insert(
      project : String,
      body : Bucket? = nil,
      enable_object_retention : Bool? = nil,
      predefined_acl : String? = nil,
      predefined_default_object_acl : String? = nil,
      projection : String? = nil,
      user_project : String? = nil,
    ) : Bucket
      req_path = "b"

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["project"] = project
      params["enableObjectRetention"] = enable_object_retention unless enable_object_retention.nil?
      params["predefinedAcl"] = predefined_acl unless predefined_acl.nil?
      params["predefinedDefaultObjectAcl"] = predefined_default_object_acl unless predefined_default_object_acl.nil?
      params["projection"] = projection unless projection.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: Bucket,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Retrieves a list of buckets for a given project.
    def list(
      project : String,
      max_results : Int64? = nil,
      page_token : String? = nil,
      prefix : String? = nil,
      projection : String? = nil,
      return_partial_success : Bool? = nil,
      soft_deleted : Bool? = nil,
      user_project : String? = nil,
    ) : Buckets
      req_path = "b"

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["project"] = project
      params["maxResults"] = max_results unless max_results.nil?
      params["pageToken"] = page_token unless page_token.nil?
      params["prefix"] = prefix unless prefix.nil?
      params["projection"] = projection unless projection.nil?
      params["returnPartialSuccess"] = return_partial_success unless return_partial_success.nil?
      params["softDeleted"] = soft_deleted unless soft_deleted.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: Buckets,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Locks retention policy on a bucket.
    def lock_retention_policy(
      bucket : String,
      if_metageneration_match : String,
      user_project : String? = nil,
    ) : Bucket
      req_path = "b/{bucket}/lockRetentionPolicy"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["ifMetagenerationMatch"] = if_metageneration_match
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: Bucket,
        http_method: "POST",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Patches a bucket. Changes to the bucket will be readable immediately after writing, but configuration changes may take time to propagate.
    def patch(
      bucket : String,
      body : Bucket? = nil,
      if_metageneration_match : String? = nil,
      if_metageneration_not_match : String? = nil,
      predefined_acl : String? = nil,
      predefined_default_object_acl : String? = nil,
      projection : String? = nil,
      user_project : String? = nil,
    ) : Bucket
      req_path = "b/{bucket}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["ifMetagenerationMatch"] = if_metageneration_match unless if_metageneration_match.nil?
      params["ifMetagenerationNotMatch"] = if_metageneration_not_match unless if_metageneration_not_match.nil?
      params["predefinedAcl"] = predefined_acl unless predefined_acl.nil?
      params["predefinedDefaultObjectAcl"] = predefined_default_object_acl unless predefined_default_object_acl.nil?
      params["projection"] = projection unless projection.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: Bucket,
        http_method: "PATCH",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Updates an IAM policy for the specified bucket.
    def set_iam_policy(
      bucket : String,
      body : Policy? = nil,
      user_project : String? = nil,
    ) : Policy
      req_path = "b/{bucket}/iam"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: Policy,
        http_method: "PUT",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Tests a set of permissions on the given bucket to see which, if any, are held by the caller.
    def test_iam_permissions(
      bucket : String,
      permissions : String,
      user_project : String? = nil,
    ) : TestIamPermissionsResponse
      req_path = "b/{bucket}/iam/testPermissions"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["permissions"] = permissions
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: TestIamPermissionsResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Updates a bucket. Changes to the bucket will be readable immediately after writing, but configuration changes may take time to propagate.
    def update(
      bucket : String,
      body : Bucket? = nil,
      if_metageneration_match : String? = nil,
      if_metageneration_not_match : String? = nil,
      predefined_acl : String? = nil,
      predefined_default_object_acl : String? = nil,
      projection : String? = nil,
      user_project : String? = nil,
    ) : Bucket
      req_path = "b/{bucket}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["ifMetagenerationMatch"] = if_metageneration_match unless if_metageneration_match.nil?
      params["ifMetagenerationNotMatch"] = if_metageneration_not_match unless if_metageneration_not_match.nil?
      params["predefinedAcl"] = predefined_acl unless predefined_acl.nil?
      params["predefinedDefaultObjectAcl"] = predefined_default_object_acl unless predefined_default_object_acl.nil?
      params["projection"] = projection unless projection.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: Bucket,
        http_method: "PUT",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end
  end
end
