# Generated by Google APIs Discovery Generator for storage (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Storage::V1
  class ChannelsService < GoogleApis::Service
    # Stop watching resources through this channel
    def stop(
      body : Channel? = nil,
    ) : Nil
      req_path = "channels/stop"

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute_raw(
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
      nil
    end
  end
end
