# Generated by Google APIs Discovery Generator for storage (v1)
# Do not edit directly.

require "../../client"
require "../../auth"
require "./anywhere_caches_service"
require "./rapid_caches_service"
require "./bucket_access_controls_service"
require "./buckets_service"
require "./operations_service"
require "./channels_service"
require "./default_object_access_controls_service"
require "./folders_service"
require "./managed_folders_service"
require "./notifications_service"
require "./object_access_controls_service"
require "./objects_service"
require "./projects_hmac_keys_service"
require "./projects_service_account_service"

module GoogleApis::Storage::V1
  # Client for the Cloud Storage JSON API API (v1).
  class Client
    DEFAULT_BASE_URL = "https://storage.googleapis.com/storage/v1/"

    getter client : GoogleApis::Client
    getter anywhere_caches : AnywhereCachesService
    getter rapid_caches : RapidCachesService
    getter bucket_access_controls : BucketAccessControlsService
    getter buckets : BucketsService
    getter operations : OperationsService
    getter channels : ChannelsService
    getter default_object_access_controls : DefaultObjectAccessControlsService
    getter folders : FoldersService
    getter managed_folders : ManagedFoldersService
    getter notifications : NotificationsService
    getter object_access_controls : ObjectAccessControlsService
    getter objects : ObjectsService
    getter projects_hmac_keys : ProjectsHmacKeysService
    getter projects_service_account : ProjectsServiceAccountService

    def initialize(
      credentials : GoogleApis::Auth::Credentials,
      base_url : String = DEFAULT_BASE_URL,
    )
      @client = GoogleApis::Client.new(credentials, base_url)
      @anywhere_caches = AnywhereCachesService.new(@client)
      @rapid_caches = RapidCachesService.new(@client)
      @bucket_access_controls = BucketAccessControlsService.new(@client)
      @buckets = BucketsService.new(@client)
      @operations = OperationsService.new(@client)
      @channels = ChannelsService.new(@client)
      @default_object_access_controls = DefaultObjectAccessControlsService.new(@client)
      @folders = FoldersService.new(@client)
      @managed_folders = ManagedFoldersService.new(@client)
      @notifications = NotificationsService.new(@client)
      @object_access_controls = ObjectAccessControlsService.new(@client)
      @objects = ObjectsService.new(@client)
      @projects_hmac_keys = ProjectsHmacKeysService.new(@client)
      @projects_service_account = ProjectsServiceAccountService.new(@client)
    end
  end
end
