# Generated by Google APIs Discovery Generator for storage (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Storage::V1
  class DefaultObjectAccessControlsService < GoogleApis::Service
    # Permanently deletes the default object ACL entry for the specified entity on the specified bucket.
    def delete(
      bucket : String,
      entity : String,
      user_project : String? = nil,
    ) : Nil
      req_path = "b/{bucket}/defaultObjectAcl/{entity}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{entity}", URI.encode_path_segment(entity.to_s))
      req_path = req_path.gsub("{+entity}", entity.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["userProject"] = user_project unless user_project.nil?

      @client.execute_raw(
        http_method: "DELETE",
        path: req_path,
        params: params,
        body: nil
      )
      nil
    end

    # Returns the default object ACL entry for the specified entity on the specified bucket.
    def get(
      bucket : String,
      entity : String,
      user_project : String? = nil,
    ) : ObjectAccessControl
      req_path = "b/{bucket}/defaultObjectAcl/{entity}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{entity}", URI.encode_path_segment(entity.to_s))
      req_path = req_path.gsub("{+entity}", entity.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: ObjectAccessControl,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Creates a new default object ACL entry on the specified bucket.
    def insert(
      bucket : String,
      body : ObjectAccessControl? = nil,
      user_project : String? = nil,
    ) : ObjectAccessControl
      req_path = "b/{bucket}/defaultObjectAcl"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: ObjectAccessControl,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Retrieves default object ACL entries on the specified bucket.
    def list(
      bucket : String,
      if_metageneration_match : String? = nil,
      if_metageneration_not_match : String? = nil,
      user_project : String? = nil,
    ) : ObjectAccessControls
      req_path = "b/{bucket}/defaultObjectAcl"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["ifMetagenerationMatch"] = if_metageneration_match unless if_metageneration_match.nil?
      params["ifMetagenerationNotMatch"] = if_metageneration_not_match unless if_metageneration_not_match.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: ObjectAccessControls,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Patches a default object ACL entry on the specified bucket.
    def patch(
      bucket : String,
      entity : String,
      body : ObjectAccessControl? = nil,
      user_project : String? = nil,
    ) : ObjectAccessControl
      req_path = "b/{bucket}/defaultObjectAcl/{entity}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{entity}", URI.encode_path_segment(entity.to_s))
      req_path = req_path.gsub("{+entity}", entity.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: ObjectAccessControl,
        http_method: "PATCH",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Updates a default object ACL entry on the specified bucket.
    def update(
      bucket : String,
      entity : String,
      body : ObjectAccessControl? = nil,
      user_project : String? = nil,
    ) : ObjectAccessControl
      req_path = "b/{bucket}/defaultObjectAcl/{entity}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{entity}", URI.encode_path_segment(entity.to_s))
      req_path = req_path.gsub("{+entity}", entity.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: ObjectAccessControl,
        http_method: "PUT",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end
  end
end
