# Generated by Google APIs Discovery Generator for storage (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Storage::V1
  class FoldersService < GoogleApis::Service
    # Permanently deletes a folder. Only applicable to buckets with hierarchical namespace enabled.
    def delete(
      bucket : String,
      folder : String,
      if_metageneration_match : String? = nil,
      if_metageneration_not_match : String? = nil,
    ) : Nil
      req_path = "b/{bucket}/folders/{folder}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{folder}", URI.encode_path_segment(folder.to_s))
      req_path = req_path.gsub("{+folder}", folder.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["ifMetagenerationMatch"] = if_metageneration_match unless if_metageneration_match.nil?
      params["ifMetagenerationNotMatch"] = if_metageneration_not_match unless if_metageneration_not_match.nil?

      @client.execute_raw(
        http_method: "DELETE",
        path: req_path,
        params: params,
        body: nil
      )
      nil
    end

    # Deletes a folder recursively. Only applicable to buckets with hierarchical namespace enabled.
    def delete_recursive(
      bucket : String,
      folder : String,
      if_metageneration_match : String? = nil,
      if_metageneration_not_match : String? = nil,
    ) : GoogleLongrunningOperation
      req_path = "b/{bucket}/folders/{folder}/deleteRecursive"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{folder}", URI.encode_path_segment(folder.to_s))
      req_path = req_path.gsub("{+folder}", folder.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["ifMetagenerationMatch"] = if_metageneration_match unless if_metageneration_match.nil?
      params["ifMetagenerationNotMatch"] = if_metageneration_not_match unless if_metageneration_not_match.nil?

      @client.execute(
        type: GoogleLongrunningOperation,
        http_method: "POST",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Returns metadata for the specified folder. Only applicable to buckets with hierarchical namespace enabled.
    def get(
      bucket : String,
      folder : String,
      if_metageneration_match : String? = nil,
      if_metageneration_not_match : String? = nil,
    ) : Folder
      req_path = "b/{bucket}/folders/{folder}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{folder}", URI.encode_path_segment(folder.to_s))
      req_path = req_path.gsub("{+folder}", folder.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["ifMetagenerationMatch"] = if_metageneration_match unless if_metageneration_match.nil?
      params["ifMetagenerationNotMatch"] = if_metageneration_not_match unless if_metageneration_not_match.nil?

      @client.execute(
        type: Folder,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Creates a new folder. Only applicable to buckets with hierarchical namespace enabled.
    def insert(
      bucket : String,
      body : Folder? = nil,
      recursive : Bool? = nil,
    ) : Folder
      req_path = "b/{bucket}/folders"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["recursive"] = recursive unless recursive.nil?

      @client.execute(
        type: Folder,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Retrieves a list of folders matching the criteria. Only applicable to buckets with hierarchical namespace enabled.
    def list(
      bucket : String,
      delimiter : String? = nil,
      end_offset : String? = nil,
      page_size : Int64? = nil,
      page_token : String? = nil,
      prefix : String? = nil,
      start_offset : String? = nil,
    ) : Folders
      req_path = "b/{bucket}/folders"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["delimiter"] = delimiter unless delimiter.nil?
      params["endOffset"] = end_offset unless end_offset.nil?
      params["pageSize"] = page_size unless page_size.nil?
      params["pageToken"] = page_token unless page_token.nil?
      params["prefix"] = prefix unless prefix.nil?
      params["startOffset"] = start_offset unless start_offset.nil?

      @client.execute(
        type: Folders,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Renames a source folder to a destination folder. Only applicable to buckets with hierarchical namespace enabled.
    def rename(
      bucket : String,
      source_folder : String,
      destination_folder : String,
      if_source_metageneration_match : String? = nil,
      if_source_metageneration_not_match : String? = nil,
    ) : GoogleLongrunningOperation
      req_path = "b/{bucket}/folders/{sourceFolder}/renameTo/folders/{destinationFolder}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{sourceFolder}", URI.encode_path_segment(source_folder.to_s))
      req_path = req_path.gsub("{+sourceFolder}", source_folder.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{destinationFolder}", URI.encode_path_segment(destination_folder.to_s))
      req_path = req_path.gsub("{+destinationFolder}", destination_folder.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["ifSourceMetagenerationMatch"] = if_source_metageneration_match unless if_source_metageneration_match.nil?
      params["ifSourceMetagenerationNotMatch"] = if_source_metageneration_not_match unless if_source_metageneration_not_match.nil?

      @client.execute(
        type: GoogleLongrunningOperation,
        http_method: "POST",
        path: req_path,
        params: params,
        body: nil
      )
    end
  end
end
