# Generated by Google APIs Discovery Generator for storage (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Storage::V1
  class ManagedFoldersService < GoogleApis::Service
    # Permanently deletes a managed folder.
    def delete(
      bucket : String,
      managed_folder : String,
      allow_non_empty : Bool? = nil,
      if_metageneration_match : String? = nil,
      if_metageneration_not_match : String? = nil,
    ) : Nil
      req_path = "b/{bucket}/managedFolders/{managedFolder}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{managedFolder}", URI.encode_path_segment(managed_folder.to_s))
      req_path = req_path.gsub("{+managedFolder}", URI.encode_path_segment(managed_folder.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["allowNonEmpty"] = allow_non_empty unless allow_non_empty.nil?
      params["ifMetagenerationMatch"] = if_metageneration_match unless if_metageneration_match.nil?
      params["ifMetagenerationNotMatch"] = if_metageneration_not_match unless if_metageneration_not_match.nil?

      @client.execute_raw(
        http_method: "DELETE",
        path: req_path,
        params: params,
        body: nil
      )
      nil
    end

    # Returns metadata of the specified managed folder.
    def get(
      bucket : String,
      managed_folder : String,
      if_metageneration_match : String? = nil,
      if_metageneration_not_match : String? = nil,
    ) : ManagedFolder
      req_path = "b/{bucket}/managedFolders/{managedFolder}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{managedFolder}", URI.encode_path_segment(managed_folder.to_s))
      req_path = req_path.gsub("{+managedFolder}", URI.encode_path_segment(managed_folder.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["ifMetagenerationMatch"] = if_metageneration_match unless if_metageneration_match.nil?
      params["ifMetagenerationNotMatch"] = if_metageneration_not_match unless if_metageneration_not_match.nil?

      @client.execute(
        type: ManagedFolder,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Updates a managed folder using patch semantics.
    def update(
      bucket : String,
      managed_folder : String,
      body : ManagedFolder? = nil,
      if_metageneration_match : String? = nil,
      if_metageneration_not_match : String? = nil,
    ) : ManagedFolder
      req_path = "b/{bucket}/managedFolders/{managedFolder}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{managedFolder}", URI.encode_path_segment(managed_folder.to_s))
      req_path = req_path.gsub("{+managedFolder}", URI.encode_path_segment(managed_folder.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["ifMetagenerationMatch"] = if_metageneration_match unless if_metageneration_match.nil?
      params["ifMetagenerationNotMatch"] = if_metageneration_not_match unless if_metageneration_not_match.nil?

      @client.execute(
        type: ManagedFolder,
        http_method: "PATCH",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Returns an IAM policy for the specified managed folder.
    def get_iam_policy(
      bucket : String,
      managed_folder : String,
      options_requested_policy_version : Int64? = nil,
      user_project : String? = nil,
    ) : Policy
      req_path = "b/{bucket}/managedFolders/{managedFolder}/iam"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{managedFolder}", URI.encode_path_segment(managed_folder.to_s))
      req_path = req_path.gsub("{+managedFolder}", URI.encode_path_segment(managed_folder.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["optionsRequestedPolicyVersion"] = options_requested_policy_version unless options_requested_policy_version.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: Policy,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Creates a new managed folder.
    def insert(
      bucket : String,
      body : ManagedFolder? = nil,
    ) : ManagedFolder
      req_path = "b/{bucket}/managedFolders"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: ManagedFolder,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Lists managed folders in the given bucket.
    def list(
      bucket : String,
      page_size : Int64? = nil,
      page_token : String? = nil,
      prefix : String? = nil,
    ) : ManagedFolders
      req_path = "b/{bucket}/managedFolders"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["pageSize"] = page_size unless page_size.nil?
      params["pageToken"] = page_token unless page_token.nil?
      params["prefix"] = prefix unless prefix.nil?

      @client.execute(
        type: ManagedFolders,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Updates an IAM policy for the specified managed folder.
    def set_iam_policy(
      bucket : String,
      managed_folder : String,
      body : Policy? = nil,
      user_project : String? = nil,
    ) : Policy
      req_path = "b/{bucket}/managedFolders/{managedFolder}/iam"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{managedFolder}", URI.encode_path_segment(managed_folder.to_s))
      req_path = req_path.gsub("{+managedFolder}", URI.encode_path_segment(managed_folder.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: Policy,
        http_method: "PUT",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Tests a set of permissions on the given managed folder to see which, if any, are held by the caller.
    def test_iam_permissions(
      bucket : String,
      managed_folder : String,
      permissions : String,
      user_project : String? = nil,
    ) : TestIamPermissionsResponse
      req_path = "b/{bucket}/managedFolders/{managedFolder}/iam/testPermissions"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{managedFolder}", URI.encode_path_segment(managed_folder.to_s))
      req_path = req_path.gsub("{+managedFolder}", URI.encode_path_segment(managed_folder.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["permissions"] = permissions
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: TestIamPermissionsResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end
  end
end
