# Generated by Google APIs Discovery Generator for storage (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Storage::V1
  class NotificationsService < GoogleApis::Service
    # Permanently deletes a notification subscription.
    def delete(
      bucket : String,
      notification : String,
      user_project : String? = nil,
    ) : Nil
      req_path = "b/{bucket}/notificationConfigs/{notification}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{notification}", URI.encode_path_segment(notification.to_s))
      req_path = req_path.gsub("{+notification}", URI.encode_path_segment(notification.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["userProject"] = user_project unless user_project.nil?

      @client.execute_raw(
        http_method: "DELETE",
        path: req_path,
        params: params,
        body: nil
      )
      nil
    end

    # View a notification configuration.
    def get(
      bucket : String,
      notification : String,
      user_project : String? = nil,
    ) : Notification
      req_path = "b/{bucket}/notificationConfigs/{notification}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{notification}", URI.encode_path_segment(notification.to_s))
      req_path = req_path.gsub("{+notification}", URI.encode_path_segment(notification.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: Notification,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Creates a notification subscription for a given bucket.
    def insert(
      bucket : String,
      body : Notification? = nil,
      user_project : String? = nil,
    ) : Notification
      req_path = "b/{bucket}/notificationConfigs"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: Notification,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Retrieves a list of notification subscriptions for a given bucket.
    def list(
      bucket : String,
      user_project : String? = nil,
    ) : Notifications
      req_path = "b/{bucket}/notificationConfigs"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: Notifications,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end
  end
end
