# Generated by Google APIs Discovery Generator for storage (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Storage::V1
  class ObjectsService < GoogleApis::Service
    # Concatenates a list of existing objects into a new object in the same bucket.
    def compose(
      destination_bucket : String,
      destination_object : String,
      body : ComposeRequest? = nil,
      destination_predefined_acl : String? = nil,
      drop_context_groups : String? = nil,
      if_generation_match : String? = nil,
      if_metageneration_match : String? = nil,
      kms_key_name : String? = nil,
      user_project : String? = nil,
    ) : Object
      req_path = "b/{destinationBucket}/o/{destinationObject}/compose"
      req_path = req_path.gsub("{destinationBucket}", URI.encode_path_segment(destination_bucket.to_s))
      req_path = req_path.gsub("{+destinationBucket}", URI.encode_path_segment(destination_bucket.to_s))
      req_path = req_path.gsub("{destinationObject}", URI.encode_path_segment(destination_object.to_s))
      req_path = req_path.gsub("{+destinationObject}", URI.encode_path_segment(destination_object.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["destinationPredefinedAcl"] = destination_predefined_acl unless destination_predefined_acl.nil?
      params["dropContextGroups"] = drop_context_groups unless drop_context_groups.nil?
      params["ifGenerationMatch"] = if_generation_match unless if_generation_match.nil?
      params["ifMetagenerationMatch"] = if_metageneration_match unless if_metageneration_match.nil?
      params["kmsKeyName"] = kms_key_name unless kms_key_name.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: Object,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Copies a source object to a destination object. Optionally overrides metadata.
    def copy(
      source_bucket : String,
      source_object : String,
      destination_bucket : String,
      destination_object : String,
      body : Object? = nil,
      destination_kms_key_name : String? = nil,
      destination_predefined_acl : String? = nil,
      if_generation_match : String? = nil,
      if_generation_not_match : String? = nil,
      if_metageneration_match : String? = nil,
      if_metageneration_not_match : String? = nil,
      if_source_generation_match : String? = nil,
      if_source_generation_not_match : String? = nil,
      if_source_metageneration_match : String? = nil,
      if_source_metageneration_not_match : String? = nil,
      projection : String? = nil,
      source_generation : String? = nil,
      user_project : String? = nil,
    ) : Object
      req_path = "b/{sourceBucket}/o/{sourceObject}/copyTo/b/{destinationBucket}/o/{destinationObject}"
      req_path = req_path.gsub("{sourceBucket}", URI.encode_path_segment(source_bucket.to_s))
      req_path = req_path.gsub("{+sourceBucket}", URI.encode_path_segment(source_bucket.to_s))
      req_path = req_path.gsub("{sourceObject}", URI.encode_path_segment(source_object.to_s))
      req_path = req_path.gsub("{+sourceObject}", URI.encode_path_segment(source_object.to_s))
      req_path = req_path.gsub("{destinationBucket}", URI.encode_path_segment(destination_bucket.to_s))
      req_path = req_path.gsub("{+destinationBucket}", URI.encode_path_segment(destination_bucket.to_s))
      req_path = req_path.gsub("{destinationObject}", URI.encode_path_segment(destination_object.to_s))
      req_path = req_path.gsub("{+destinationObject}", URI.encode_path_segment(destination_object.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["destinationKmsKeyName"] = destination_kms_key_name unless destination_kms_key_name.nil?
      params["destinationPredefinedAcl"] = destination_predefined_acl unless destination_predefined_acl.nil?
      params["ifGenerationMatch"] = if_generation_match unless if_generation_match.nil?
      params["ifGenerationNotMatch"] = if_generation_not_match unless if_generation_not_match.nil?
      params["ifMetagenerationMatch"] = if_metageneration_match unless if_metageneration_match.nil?
      params["ifMetagenerationNotMatch"] = if_metageneration_not_match unless if_metageneration_not_match.nil?
      params["ifSourceGenerationMatch"] = if_source_generation_match unless if_source_generation_match.nil?
      params["ifSourceGenerationNotMatch"] = if_source_generation_not_match unless if_source_generation_not_match.nil?
      params["ifSourceMetagenerationMatch"] = if_source_metageneration_match unless if_source_metageneration_match.nil?
      params["ifSourceMetagenerationNotMatch"] = if_source_metageneration_not_match unless if_source_metageneration_not_match.nil?
      params["projection"] = projection unless projection.nil?
      params["sourceGeneration"] = source_generation unless source_generation.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: Object,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Deletes an object and its metadata. Deletions are permanent if versioning is not enabled for the bucket, or if the generation parameter is used.
    def delete(
      bucket : String,
      object : String,
      generation : String? = nil,
      if_generation_match : String? = nil,
      if_generation_not_match : String? = nil,
      if_metageneration_match : String? = nil,
      if_metageneration_not_match : String? = nil,
      user_project : String? = nil,
    ) : Nil
      req_path = "b/{bucket}/o/{object}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{object}", URI.encode_path_segment(object.to_s))
      req_path = req_path.gsub("{+object}", URI.encode_path_segment(object.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["generation"] = generation unless generation.nil?
      params["ifGenerationMatch"] = if_generation_match unless if_generation_match.nil?
      params["ifGenerationNotMatch"] = if_generation_not_match unless if_generation_not_match.nil?
      params["ifMetagenerationMatch"] = if_metageneration_match unless if_metageneration_match.nil?
      params["ifMetagenerationNotMatch"] = if_metageneration_not_match unless if_metageneration_not_match.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute_raw(
        http_method: "DELETE",
        path: req_path,
        params: params,
        body: nil
      )
      nil
    end

    # Retrieves an object or its metadata.
    def get(
      bucket : String,
      object : String,
      generation : String? = nil,
      if_generation_match : String? = nil,
      if_generation_not_match : String? = nil,
      if_metageneration_match : String? = nil,
      if_metageneration_not_match : String? = nil,
      projection : String? = nil,
      restore_token : String? = nil,
      soft_deleted : Bool? = nil,
      user_project : String? = nil,
    ) : Object
      req_path = "b/{bucket}/o/{object}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{object}", URI.encode_path_segment(object.to_s))
      req_path = req_path.gsub("{+object}", URI.encode_path_segment(object.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["generation"] = generation unless generation.nil?
      params["ifGenerationMatch"] = if_generation_match unless if_generation_match.nil?
      params["ifGenerationNotMatch"] = if_generation_not_match unless if_generation_not_match.nil?
      params["ifMetagenerationMatch"] = if_metageneration_match unless if_metageneration_match.nil?
      params["ifMetagenerationNotMatch"] = if_metageneration_not_match unless if_metageneration_not_match.nil?
      params["projection"] = projection unless projection.nil?
      params["restoreToken"] = restore_token unless restore_token.nil?
      params["softDeleted"] = soft_deleted unless soft_deleted.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: Object,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Returns an IAM policy for the specified object.
    def get_iam_policy(
      bucket : String,
      object : String,
      generation : String? = nil,
      user_project : String? = nil,
    ) : Policy
      req_path = "b/{bucket}/o/{object}/iam"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{object}", URI.encode_path_segment(object.to_s))
      req_path = req_path.gsub("{+object}", URI.encode_path_segment(object.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["generation"] = generation unless generation.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: Policy,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Stores a new object and metadata.
    def insert(
      bucket : String,
      body : Object? = nil,
      content_encoding : String? = nil,
      if_generation_match : String? = nil,
      if_generation_not_match : String? = nil,
      if_metageneration_match : String? = nil,
      if_metageneration_not_match : String? = nil,
      kms_key_name : String? = nil,
      name : String? = nil,
      predefined_acl : String? = nil,
      projection : String? = nil,
      user_project : String? = nil,
    ) : Object
      req_path = "b/{bucket}/o"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["contentEncoding"] = content_encoding unless content_encoding.nil?
      params["ifGenerationMatch"] = if_generation_match unless if_generation_match.nil?
      params["ifGenerationNotMatch"] = if_generation_not_match unless if_generation_not_match.nil?
      params["ifMetagenerationMatch"] = if_metageneration_match unless if_metageneration_match.nil?
      params["ifMetagenerationNotMatch"] = if_metageneration_not_match unless if_metageneration_not_match.nil?
      params["kmsKeyName"] = kms_key_name unless kms_key_name.nil?
      params["name"] = name unless name.nil?
      params["predefinedAcl"] = predefined_acl unless predefined_acl.nil?
      params["projection"] = projection unless projection.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: Object,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Retrieves a list of objects matching the criteria.
    def list(
      bucket : String,
      delimiter : String? = nil,
      end_offset : String? = nil,
      filter : String? = nil,
      include_folders_as_prefixes : Bool? = nil,
      include_trailing_delimiter : Bool? = nil,
      match_glob : String? = nil,
      max_results : Int64? = nil,
      page_token : String? = nil,
      prefix : String? = nil,
      projection : String? = nil,
      soft_deleted : Bool? = nil,
      start_offset : String? = nil,
      user_project : String? = nil,
      versions : Bool? = nil,
    ) : Objects
      req_path = "b/{bucket}/o"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["delimiter"] = delimiter unless delimiter.nil?
      params["endOffset"] = end_offset unless end_offset.nil?
      params["filter"] = filter unless filter.nil?
      params["includeFoldersAsPrefixes"] = include_folders_as_prefixes unless include_folders_as_prefixes.nil?
      params["includeTrailingDelimiter"] = include_trailing_delimiter unless include_trailing_delimiter.nil?
      params["matchGlob"] = match_glob unless match_glob.nil?
      params["maxResults"] = max_results unless max_results.nil?
      params["pageToken"] = page_token unless page_token.nil?
      params["prefix"] = prefix unless prefix.nil?
      params["projection"] = projection unless projection.nil?
      params["softDeleted"] = soft_deleted unless soft_deleted.nil?
      params["startOffset"] = start_offset unless start_offset.nil?
      params["userProject"] = user_project unless user_project.nil?
      params["versions"] = versions unless versions.nil?

      @client.execute(
        type: Objects,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Patches an object's metadata.
    def patch(
      bucket : String,
      object : String,
      body : Object? = nil,
      generation : String? = nil,
      if_generation_match : String? = nil,
      if_generation_not_match : String? = nil,
      if_metageneration_match : String? = nil,
      if_metageneration_not_match : String? = nil,
      override_unlocked_retention : Bool? = nil,
      predefined_acl : String? = nil,
      projection : String? = nil,
      user_project : String? = nil,
    ) : Object
      req_path = "b/{bucket}/o/{object}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{object}", URI.encode_path_segment(object.to_s))
      req_path = req_path.gsub("{+object}", URI.encode_path_segment(object.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["generation"] = generation unless generation.nil?
      params["ifGenerationMatch"] = if_generation_match unless if_generation_match.nil?
      params["ifGenerationNotMatch"] = if_generation_not_match unless if_generation_not_match.nil?
      params["ifMetagenerationMatch"] = if_metageneration_match unless if_metageneration_match.nil?
      params["ifMetagenerationNotMatch"] = if_metageneration_not_match unless if_metageneration_not_match.nil?
      params["overrideUnlockedRetention"] = override_unlocked_retention unless override_unlocked_retention.nil?
      params["predefinedAcl"] = predefined_acl unless predefined_acl.nil?
      params["projection"] = projection unless projection.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: Object,
        http_method: "PATCH",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Rewrites a source object to a destination object. Optionally overrides metadata.
    def rewrite(
      source_bucket : String,
      source_object : String,
      destination_bucket : String,
      destination_object : String,
      body : Object? = nil,
      destination_kms_key_name : String? = nil,
      destination_predefined_acl : String? = nil,
      drop_context_groups : String? = nil,
      if_generation_match : String? = nil,
      if_generation_not_match : String? = nil,
      if_metageneration_match : String? = nil,
      if_metageneration_not_match : String? = nil,
      if_source_generation_match : String? = nil,
      if_source_generation_not_match : String? = nil,
      if_source_metageneration_match : String? = nil,
      if_source_metageneration_not_match : String? = nil,
      max_bytes_rewritten_per_call : String? = nil,
      projection : String? = nil,
      rewrite_token : String? = nil,
      source_generation : String? = nil,
      user_project : String? = nil,
    ) : RewriteResponse
      req_path = "b/{sourceBucket}/o/{sourceObject}/rewriteTo/b/{destinationBucket}/o/{destinationObject}"
      req_path = req_path.gsub("{sourceBucket}", URI.encode_path_segment(source_bucket.to_s))
      req_path = req_path.gsub("{+sourceBucket}", URI.encode_path_segment(source_bucket.to_s))
      req_path = req_path.gsub("{sourceObject}", URI.encode_path_segment(source_object.to_s))
      req_path = req_path.gsub("{+sourceObject}", URI.encode_path_segment(source_object.to_s))
      req_path = req_path.gsub("{destinationBucket}", URI.encode_path_segment(destination_bucket.to_s))
      req_path = req_path.gsub("{+destinationBucket}", URI.encode_path_segment(destination_bucket.to_s))
      req_path = req_path.gsub("{destinationObject}", URI.encode_path_segment(destination_object.to_s))
      req_path = req_path.gsub("{+destinationObject}", URI.encode_path_segment(destination_object.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["destinationKmsKeyName"] = destination_kms_key_name unless destination_kms_key_name.nil?
      params["destinationPredefinedAcl"] = destination_predefined_acl unless destination_predefined_acl.nil?
      params["dropContextGroups"] = drop_context_groups unless drop_context_groups.nil?
      params["ifGenerationMatch"] = if_generation_match unless if_generation_match.nil?
      params["ifGenerationNotMatch"] = if_generation_not_match unless if_generation_not_match.nil?
      params["ifMetagenerationMatch"] = if_metageneration_match unless if_metageneration_match.nil?
      params["ifMetagenerationNotMatch"] = if_metageneration_not_match unless if_metageneration_not_match.nil?
      params["ifSourceGenerationMatch"] = if_source_generation_match unless if_source_generation_match.nil?
      params["ifSourceGenerationNotMatch"] = if_source_generation_not_match unless if_source_generation_not_match.nil?
      params["ifSourceMetagenerationMatch"] = if_source_metageneration_match unless if_source_metageneration_match.nil?
      params["ifSourceMetagenerationNotMatch"] = if_source_metageneration_not_match unless if_source_metageneration_not_match.nil?
      params["maxBytesRewrittenPerCall"] = max_bytes_rewritten_per_call unless max_bytes_rewritten_per_call.nil?
      params["projection"] = projection unless projection.nil?
      params["rewriteToken"] = rewrite_token unless rewrite_token.nil?
      params["sourceGeneration"] = source_generation unless source_generation.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: RewriteResponse,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Moves the source object to the destination object in the same bucket.
    def move(
      bucket : String,
      source_object : String,
      destination_object : String,
      if_generation_match : String? = nil,
      if_generation_not_match : String? = nil,
      if_metageneration_match : String? = nil,
      if_metageneration_not_match : String? = nil,
      if_source_generation_match : String? = nil,
      if_source_generation_not_match : String? = nil,
      if_source_metageneration_match : String? = nil,
      if_source_metageneration_not_match : String? = nil,
      projection : String? = nil,
      user_project : String? = nil,
    ) : Object
      req_path = "b/{bucket}/o/{sourceObject}/moveTo/o/{destinationObject}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{sourceObject}", URI.encode_path_segment(source_object.to_s))
      req_path = req_path.gsub("{+sourceObject}", URI.encode_path_segment(source_object.to_s))
      req_path = req_path.gsub("{destinationObject}", URI.encode_path_segment(destination_object.to_s))
      req_path = req_path.gsub("{+destinationObject}", URI.encode_path_segment(destination_object.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["ifGenerationMatch"] = if_generation_match unless if_generation_match.nil?
      params["ifGenerationNotMatch"] = if_generation_not_match unless if_generation_not_match.nil?
      params["ifMetagenerationMatch"] = if_metageneration_match unless if_metageneration_match.nil?
      params["ifMetagenerationNotMatch"] = if_metageneration_not_match unless if_metageneration_not_match.nil?
      params["ifSourceGenerationMatch"] = if_source_generation_match unless if_source_generation_match.nil?
      params["ifSourceGenerationNotMatch"] = if_source_generation_not_match unless if_source_generation_not_match.nil?
      params["ifSourceMetagenerationMatch"] = if_source_metageneration_match unless if_source_metageneration_match.nil?
      params["ifSourceMetagenerationNotMatch"] = if_source_metageneration_not_match unless if_source_metageneration_not_match.nil?
      params["projection"] = projection unless projection.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: Object,
        http_method: "POST",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Updates an IAM policy for the specified object.
    def set_iam_policy(
      bucket : String,
      object : String,
      body : Policy? = nil,
      generation : String? = nil,
      user_project : String? = nil,
    ) : Policy
      req_path = "b/{bucket}/o/{object}/iam"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{object}", URI.encode_path_segment(object.to_s))
      req_path = req_path.gsub("{+object}", URI.encode_path_segment(object.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["generation"] = generation unless generation.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: Policy,
        http_method: "PUT",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Tests a set of permissions on the given object to see which, if any, are held by the caller.
    def test_iam_permissions(
      bucket : String,
      object : String,
      permissions : String,
      generation : String? = nil,
      user_project : String? = nil,
    ) : TestIamPermissionsResponse
      req_path = "b/{bucket}/o/{object}/iam/testPermissions"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{object}", URI.encode_path_segment(object.to_s))
      req_path = req_path.gsub("{+object}", URI.encode_path_segment(object.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["permissions"] = permissions
      params["generation"] = generation unless generation.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: TestIamPermissionsResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Updates an object's metadata.
    def update(
      bucket : String,
      object : String,
      body : Object? = nil,
      generation : String? = nil,
      if_generation_match : String? = nil,
      if_generation_not_match : String? = nil,
      if_metageneration_match : String? = nil,
      if_metageneration_not_match : String? = nil,
      override_unlocked_retention : Bool? = nil,
      predefined_acl : String? = nil,
      projection : String? = nil,
      user_project : String? = nil,
    ) : Object
      req_path = "b/{bucket}/o/{object}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{object}", URI.encode_path_segment(object.to_s))
      req_path = req_path.gsub("{+object}", URI.encode_path_segment(object.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["generation"] = generation unless generation.nil?
      params["ifGenerationMatch"] = if_generation_match unless if_generation_match.nil?
      params["ifGenerationNotMatch"] = if_generation_not_match unless if_generation_not_match.nil?
      params["ifMetagenerationMatch"] = if_metageneration_match unless if_metageneration_match.nil?
      params["ifMetagenerationNotMatch"] = if_metageneration_not_match unless if_metageneration_not_match.nil?
      params["overrideUnlockedRetention"] = override_unlocked_retention unless override_unlocked_retention.nil?
      params["predefinedAcl"] = predefined_acl unless predefined_acl.nil?
      params["projection"] = projection unless projection.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: Object,
        http_method: "PUT",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Restores a soft-deleted object.
    def restore(
      bucket : String,
      object : String,
      generation : String,
      copy_source_acl : Bool? = nil,
      if_generation_match : String? = nil,
      if_generation_not_match : String? = nil,
      if_metageneration_match : String? = nil,
      if_metageneration_not_match : String? = nil,
      projection : String? = nil,
      restore_token : String? = nil,
      user_project : String? = nil,
    ) : Object
      req_path = "b/{bucket}/o/{object}/restore"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{object}", URI.encode_path_segment(object.to_s))
      req_path = req_path.gsub("{+object}", URI.encode_path_segment(object.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["generation"] = generation
      params["copySourceAcl"] = copy_source_acl unless copy_source_acl.nil?
      params["ifGenerationMatch"] = if_generation_match unless if_generation_match.nil?
      params["ifGenerationNotMatch"] = if_generation_not_match unless if_generation_not_match.nil?
      params["ifMetagenerationMatch"] = if_metageneration_match unless if_metageneration_match.nil?
      params["ifMetagenerationNotMatch"] = if_metageneration_not_match unless if_metageneration_not_match.nil?
      params["projection"] = projection unless projection.nil?
      params["restoreToken"] = restore_token unless restore_token.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: Object,
        http_method: "POST",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Initiates a long-running bulk restore operation on the specified bucket.
    def bulk_restore(
      bucket : String,
      body : BulkRestoreObjectsRequest? = nil,
    ) : GoogleLongrunningOperation
      req_path = "b/{bucket}/o/bulkRestore"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleLongrunningOperation,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Retrieves a specific object context with its extended data for a given object.
    def view_full_context(
      bucket : String,
      object : String,
      context_key : String,
      generation : String? = nil,
      user_project : String? = nil,
    ) : ObjectFullContext
      req_path = "b/{bucket}/o/{object}/viewFullContext"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{object}", URI.encode_path_segment(object.to_s))
      req_path = req_path.gsub("{+object}", URI.encode_path_segment(object.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["contextKey"] = context_key
      params["generation"] = generation unless generation.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: ObjectFullContext,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end
  end
end
