# Generated by Google APIs Discovery Generator for storage (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Storage::V1
  class ObjectAccessControlsService < GoogleApis::Service
    # Permanently deletes the ACL entry for the specified entity on the specified object.
    def delete(
      bucket : String,
      object : String,
      entity : String,
      generation : String? = nil,
      user_project : String? = nil,
    ) : Nil
      req_path = "b/{bucket}/o/{object}/acl/{entity}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{object}", URI.encode_path_segment(object.to_s))
      req_path = req_path.gsub("{+object}", URI.encode_path_segment(object.to_s))
      req_path = req_path.gsub("{entity}", URI.encode_path_segment(entity.to_s))
      req_path = req_path.gsub("{+entity}", URI.encode_path_segment(entity.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["generation"] = generation unless generation.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute_raw(
        http_method: "DELETE",
        path: req_path,
        params: params,
        body: nil
      )
      nil
    end

    # Returns the ACL entry for the specified entity on the specified object.
    def get(
      bucket : String,
      object : String,
      entity : String,
      generation : String? = nil,
      user_project : String? = nil,
    ) : ObjectAccessControl
      req_path = "b/{bucket}/o/{object}/acl/{entity}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{object}", URI.encode_path_segment(object.to_s))
      req_path = req_path.gsub("{+object}", URI.encode_path_segment(object.to_s))
      req_path = req_path.gsub("{entity}", URI.encode_path_segment(entity.to_s))
      req_path = req_path.gsub("{+entity}", URI.encode_path_segment(entity.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["generation"] = generation unless generation.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: ObjectAccessControl,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Creates a new ACL entry on the specified object.
    def insert(
      bucket : String,
      object : String,
      body : ObjectAccessControl? = nil,
      generation : String? = nil,
      user_project : String? = nil,
    ) : ObjectAccessControl
      req_path = "b/{bucket}/o/{object}/acl"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{object}", URI.encode_path_segment(object.to_s))
      req_path = req_path.gsub("{+object}", URI.encode_path_segment(object.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["generation"] = generation unless generation.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: ObjectAccessControl,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Retrieves ACL entries on the specified object.
    def list(
      bucket : String,
      object : String,
      generation : String? = nil,
      user_project : String? = nil,
    ) : ObjectAccessControls
      req_path = "b/{bucket}/o/{object}/acl"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{object}", URI.encode_path_segment(object.to_s))
      req_path = req_path.gsub("{+object}", URI.encode_path_segment(object.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["generation"] = generation unless generation.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: ObjectAccessControls,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Patches an ACL entry on the specified object.
    def patch(
      bucket : String,
      object : String,
      entity : String,
      body : ObjectAccessControl? = nil,
      generation : String? = nil,
      user_project : String? = nil,
    ) : ObjectAccessControl
      req_path = "b/{bucket}/o/{object}/acl/{entity}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{object}", URI.encode_path_segment(object.to_s))
      req_path = req_path.gsub("{+object}", URI.encode_path_segment(object.to_s))
      req_path = req_path.gsub("{entity}", URI.encode_path_segment(entity.to_s))
      req_path = req_path.gsub("{+entity}", URI.encode_path_segment(entity.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["generation"] = generation unless generation.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: ObjectAccessControl,
        http_method: "PATCH",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Updates an ACL entry on the specified object.
    def update(
      bucket : String,
      object : String,
      entity : String,
      body : ObjectAccessControl? = nil,
      generation : String? = nil,
      user_project : String? = nil,
    ) : ObjectAccessControl
      req_path = "b/{bucket}/o/{object}/acl/{entity}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{object}", URI.encode_path_segment(object.to_s))
      req_path = req_path.gsub("{+object}", URI.encode_path_segment(object.to_s))
      req_path = req_path.gsub("{entity}", URI.encode_path_segment(entity.to_s))
      req_path = req_path.gsub("{+entity}", URI.encode_path_segment(entity.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["generation"] = generation unless generation.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: ObjectAccessControl,
        http_method: "PUT",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end
  end
end
