# Generated by Google APIs Discovery Generator for storage (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Storage::V1
  class OperationsService < GoogleApis::Service
    # Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed.
    def cancel(
      bucket : String,
      operation_id : String,
    ) : Nil
      req_path = "b/{bucket}/operations/{operationId}/cancel"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{operationId}", URI.encode_path_segment(operation_id.to_s))
      req_path = req_path.gsub("{+operationId}", URI.encode_path_segment(operation_id.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute_raw(
        http_method: "POST",
        path: req_path,
        params: params,
        body: nil
      )
      nil
    end

    # Gets the latest state of a long-running operation.
    def get(
      bucket : String,
      operation_id : String,
    ) : GoogleLongrunningOperation
      req_path = "b/{bucket}/operations/{operationId}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{operationId}", URI.encode_path_segment(operation_id.to_s))
      req_path = req_path.gsub("{+operationId}", URI.encode_path_segment(operation_id.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleLongrunningOperation,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Starts asynchronous advancement of the relocate bucket operation in the case of required write downtime, to allow it to lock the bucket at the source location, and proceed with the bucket location swap. The server makes a best effort to advance the relocate bucket operation, but success is not guaranteed.
    def advance_relocate_bucket(
      bucket : String,
      operation_id : String,
      body : AdvanceRelocateBucketOperationRequest? = nil,
    ) : Nil
      req_path = "b/{bucket}/operations/{operationId}/advanceRelocateBucket"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{operationId}", URI.encode_path_segment(operation_id.to_s))
      req_path = req_path.gsub("{+operationId}", URI.encode_path_segment(operation_id.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute_raw(
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
      nil
    end

    # Lists operations that match the specified filter in the request.
    def list(
      bucket : String,
      filter : String? = nil,
      page_size : Int64? = nil,
      page_token : String? = nil,
    ) : GoogleLongrunningListOperationsResponse
      req_path = "b/{bucket}/operations"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", URI.encode_path_segment(bucket.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["filter"] = filter unless filter.nil?
      params["pageSize"] = page_size unless page_size.nil?
      params["pageToken"] = page_token unless page_token.nil?

      @client.execute(
        type: GoogleLongrunningListOperationsResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end
  end
end
