# Generated by Google APIs Discovery Generator for storage (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Storage::V1
  class ProjectsServiceAccountService < GoogleApis::Service
    # Get the email address of this project's Google Cloud Storage service account.
    def get(
      project_id : String,
      user_project : String? = nil,
    ) : ServiceAccount
      req_path = "projects/{projectId}/serviceAccount"
      req_path = req_path.gsub("{projectId}", URI.encode_path_segment(project_id.to_s))
      req_path = req_path.gsub("{+projectId}", URI.encode_path_segment(project_id.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: ServiceAccount,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end
  end
end
