# Generated by Google APIs Discovery Generator for storage (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Storage::V1
  class ProjectsHmacKeysService < GoogleApis::Service
    # Creates a new HMAC key for the specified service account.
    def create(
      project_id : String,
      service_account_email : String,
      user_project : String? = nil,
    ) : HmacKey
      req_path = "projects/{projectId}/hmacKeys"
      req_path = req_path.gsub("{projectId}", URI.encode_path_segment(project_id.to_s))
      req_path = req_path.gsub("{+projectId}", URI.encode_path_segment(project_id.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["serviceAccountEmail"] = service_account_email
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: HmacKey,
        http_method: "POST",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Deletes an HMAC key.
    def delete(
      project_id : String,
      access_id : String,
      user_project : String? = nil,
    ) : Nil
      req_path = "projects/{projectId}/hmacKeys/{accessId}"
      req_path = req_path.gsub("{projectId}", URI.encode_path_segment(project_id.to_s))
      req_path = req_path.gsub("{+projectId}", URI.encode_path_segment(project_id.to_s))
      req_path = req_path.gsub("{accessId}", URI.encode_path_segment(access_id.to_s))
      req_path = req_path.gsub("{+accessId}", URI.encode_path_segment(access_id.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["userProject"] = user_project unless user_project.nil?

      @client.execute_raw(
        http_method: "DELETE",
        path: req_path,
        params: params,
        body: nil
      )
      nil
    end

    # Retrieves an HMAC key's metadata
    def get(
      project_id : String,
      access_id : String,
      user_project : String? = nil,
    ) : HmacKeyMetadata
      req_path = "projects/{projectId}/hmacKeys/{accessId}"
      req_path = req_path.gsub("{projectId}", URI.encode_path_segment(project_id.to_s))
      req_path = req_path.gsub("{+projectId}", URI.encode_path_segment(project_id.to_s))
      req_path = req_path.gsub("{accessId}", URI.encode_path_segment(access_id.to_s))
      req_path = req_path.gsub("{+accessId}", URI.encode_path_segment(access_id.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: HmacKeyMetadata,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Retrieves a list of HMAC keys matching the criteria.
    def list(
      project_id : String,
      max_results : Int64? = nil,
      page_token : String? = nil,
      service_account_email : String? = nil,
      show_deleted_keys : Bool? = nil,
      user_project : String? = nil,
    ) : HmacKeysMetadata
      req_path = "projects/{projectId}/hmacKeys"
      req_path = req_path.gsub("{projectId}", URI.encode_path_segment(project_id.to_s))
      req_path = req_path.gsub("{+projectId}", URI.encode_path_segment(project_id.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["maxResults"] = max_results unless max_results.nil?
      params["pageToken"] = page_token unless page_token.nil?
      params["serviceAccountEmail"] = service_account_email unless service_account_email.nil?
      params["showDeletedKeys"] = show_deleted_keys unless show_deleted_keys.nil?
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: HmacKeysMetadata,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Updates the state of an HMAC key. See the [HMAC Key resource descriptor](https://cloud.google.com/storage/docs/json_api/v1/projects/hmacKeys/update#request-body) for valid states.
    def update(
      project_id : String,
      access_id : String,
      body : HmacKeyMetadata? = nil,
      user_project : String? = nil,
    ) : HmacKeyMetadata
      req_path = "projects/{projectId}/hmacKeys/{accessId}"
      req_path = req_path.gsub("{projectId}", URI.encode_path_segment(project_id.to_s))
      req_path = req_path.gsub("{+projectId}", URI.encode_path_segment(project_id.to_s))
      req_path = req_path.gsub("{accessId}", URI.encode_path_segment(access_id.to_s))
      req_path = req_path.gsub("{+accessId}", URI.encode_path_segment(access_id.to_s))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["userProject"] = user_project unless user_project.nil?

      @client.execute(
        type: HmacKeyMetadata,
        http_method: "PUT",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end
  end
end
