# Generated by Google APIs Discovery Generator for storage (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Storage::V1
  class RapidCachesService < GoogleApis::Service
    # Creates a Rapid Cache instance.
    def insert(
      bucket : String,
      body : RapidCache? = nil,
    ) : GoogleLongrunningOperation
      req_path = "b/{bucket}/rapidCaches"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleLongrunningOperation,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Updates the configuration of a Rapid Cache instance.
    def update(
      bucket : String,
      rapid_cache_id : String,
      body : RapidCache? = nil,
    ) : GoogleLongrunningOperation
      req_path = "b/{bucket}/rapidCaches/{rapidCacheId}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{rapidCacheId}", URI.encode_path_segment(rapid_cache_id.to_s))
      req_path = req_path.gsub("{+rapidCacheId}", rapid_cache_id.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleLongrunningOperation,
        http_method: "PATCH",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Returns the metadata of a Rapid Cache instance.
    def get(
      bucket : String,
      rapid_cache_id : String,
    ) : RapidCache
      req_path = "b/{bucket}/rapidCaches/{rapidCacheId}"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{rapidCacheId}", URI.encode_path_segment(rapid_cache_id.to_s))
      req_path = req_path.gsub("{+rapidCacheId}", rapid_cache_id.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: RapidCache,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Returns a list of Rapid Cache instances of the bucket.
    def list(
      bucket : String,
      page_size : Int64? = nil,
      page_token : String? = nil,
    ) : RapidCaches
      req_path = "b/{bucket}/rapidCaches"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["pageSize"] = page_size unless page_size.nil?
      params["pageToken"] = page_token unless page_token.nil?

      @client.execute(
        type: RapidCaches,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Disables a Rapid Cache instance.
    def disable(
      bucket : String,
      rapid_cache_id : String,
    ) : GoogleLongrunningOperation
      req_path = "b/{bucket}/rapidCaches/{rapidCacheId}/disable"
      req_path = req_path.gsub("{bucket}", URI.encode_path_segment(bucket.to_s))
      req_path = req_path.gsub("{+bucket}", bucket.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{rapidCacheId}", URI.encode_path_segment(rapid_cache_id.to_s))
      req_path = req_path.gsub("{+rapidCacheId}", rapid_cache_id.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleLongrunningOperation,
        http_method: "POST",
        path: req_path,
        params: params,
        body: nil
      )
    end
  end
end
