# Generated by Google APIs Discovery Generator for storage (v1)
# Do not edit directly.

require "json"

module GoogleApis::Storage::V1
  # An AdvanceRelocateBucketOperation request.
  class AdvanceRelocateBucketOperationRequest
    include JSON::Serializable

    # Specifies the duration after which the relocation will revert to the sync stage if the relocation hasn't succeeded. Optional, if not supplied, a default value of 12h will be used.
    @[JSON::Field(key: "ttl")]
    property ttl : String? = nil

    # Specifies the time when the relocation will revert to the sync stage if the relocation hasn't succeeded.
    @[JSON::Field(key: "expireTime")]
    property expire_time : String? = nil

    def initialize(
      @ttl : String? = nil,
      @expire_time : String? = nil,
    )
    end
  end

  # An Anywhere Cache instance.
  class AnywhereCache
    include JSON::Serializable

    # The kind of item this is. For Anywhere Cache, this is always storage#anywhereCache.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    # The ID of the resource, including the project number, bucket name and anywhere cache ID.
    @[JSON::Field(key: "id")]
    property id : String? = nil

    # The link to this cache instance.
    @[JSON::Field(key: "selfLink")]
    property self_link : String? = nil

    # The name of the bucket containing this cache instance.
    @[JSON::Field(key: "bucket")]
    property bucket : String? = nil

    # The ID of the Anywhere cache instance.
    @[JSON::Field(key: "anywhereCacheId")]
    property anywhere_cache_id : String? = nil

    # The zone in which the cache instance is running. For example, us-central1-a.
    @[JSON::Field(key: "zone")]
    property zone : String? = nil

    # The current state of the cache instance.
    @[JSON::Field(key: "state")]
    property state : String? = nil

    # The creation time of the cache instance in RFC 3339 format.
    @[JSON::Field(key: "createTime")]
    property create_time : String? = nil

    # The modification time of the cache instance metadata in RFC 3339 format.
    @[JSON::Field(key: "updateTime")]
    property update_time : String? = nil

    # The TTL of all cache entries in whole seconds. e.g., "7200s".
    @[JSON::Field(key: "ttl")]
    property ttl : String? = nil

    # The cache-level entry admission policy.
    @[JSON::Field(key: "admissionPolicy")]
    property admission_policy : String? = nil

    # True if the cache instance has an active Update long-running operation.
    @[JSON::Field(key: "pendingUpdate")]
    property pending_update : Bool? = nil

    # Specifies whether objects are ingested into the cache upon write.
    @[JSON::Field(key: "ingestOnWrite")]
    property ingest_on_write : Bool? = nil

    def initialize(
      @kind : String? = nil,
      @id : String? = nil,
      @self_link : String? = nil,
      @bucket : String? = nil,
      @anywhere_cache_id : String? = nil,
      @zone : String? = nil,
      @state : String? = nil,
      @create_time : String? = nil,
      @update_time : String? = nil,
      @ttl : String? = nil,
      @admission_policy : String? = nil,
      @pending_update : Bool? = nil,
      @ingest_on_write : Bool? = nil,
    )
    end
  end

  # A list of Anywhere Caches.
  class AnywhereCaches
    include JSON::Serializable

    # The kind of item this is. For lists of Anywhere Caches, this is always storage#anywhereCaches.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    # The continuation token, used to page through large result sets. Provide this value in a subsequent request to return the next page of results.
    @[JSON::Field(key: "nextPageToken")]
    property next_page_token : String? = nil

    # The list of items.
    @[JSON::Field(key: "items")]
    property items : Array(AnywhereCache)? = nil

    def initialize(
      @kind : String? = nil,
      @next_page_token : String? = nil,
      @items : Array(AnywhereCache)? = nil,
    )
    end
  end

  # A bucket.
  class Bucket
    include JSON::Serializable

    # Access controls on the bucket.
    @[JSON::Field(key: "acl")]
    property acl : Array(BucketAccessControl)? = nil

    # The bucket's billing configuration.
    @[JSON::Field(key: "billing")]
    property billing : JSON::Any? = nil

    # The bucket's Cross-Origin Resource Sharing (CORS) configuration.
    @[JSON::Field(key: "cors")]
    property cors : Array(JSON::Any)? = nil

    # The bucket's custom placement configuration for Custom Dual Regions.
    @[JSON::Field(key: "customPlacementConfig")]
    property custom_placement_config : JSON::Any? = nil

    # The default value for event-based hold on newly created objects in this bucket. Event-based hold is a way to retain objects indefinitely until an event occurs, signified by the hold's release. After being released, such objects will be subject to bucket-level retention (if any). One sample use case of this flag is for banks to hold loan documents for at least 3 years after loan is paid in full. Here, bucket-level retention is 3 years and the event is loan being paid in full. In this example, these objects will be held intact for any number of years until the event has occurred (event-based hold on the object is released) and then 3 more years after that. That means retention duration of the objects begins from the moment event-based hold transitioned from true to false. Objects under event-based hold cannot be deleted, overwritten or archived until the hold is removed.
    @[JSON::Field(key: "defaultEventBasedHold")]
    property default_event_based_hold : Bool? = nil

    # Default access controls to apply to new objects when no ACL is provided.
    @[JSON::Field(key: "defaultObjectAcl")]
    property default_object_acl : Array(ObjectAccessControl)? = nil

    # Encryption configuration for a bucket.
    @[JSON::Field(key: "encryption")]
    property encryption : JSON::Any? = nil

    # HTTP 1.1 Entity tag for the bucket.
    @[JSON::Field(key: "etag")]
    property etag : String? = nil

    # The bucket's hierarchical namespace configuration.
    @[JSON::Field(key: "hierarchicalNamespace")]
    property hierarchical_namespace : JSON::Any? = nil

    # The bucket's IAM configuration.
    @[JSON::Field(key: "iamConfiguration")]
    property iam_configuration : JSON::Any? = nil

    # The ID of the bucket. For buckets, the id and name properties are the same.
    @[JSON::Field(key: "id")]
    property id : String? = nil

    # The bucket's IP filter configuration. Specifies the network sources that are allowed to access the operations on the bucket, as well as its underlying objects. Only enforced when the mode is set to 'Enabled'.
    @[JSON::Field(key: "ipFilter")]
    property ip_filter : JSON::Any? = nil

    # The kind of item this is. For buckets, this is always storage#bucket.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    # User-provided labels, in key/value pairs.
    @[JSON::Field(key: "labels")]
    property labels : Hash(String, String)? = nil

    # The bucket's lifecycle configuration. See [Lifecycle Management](https://cloud.google.com/storage/docs/lifecycle) for more information.
    @[JSON::Field(key: "lifecycle")]
    property lifecycle : JSON::Any? = nil

    # The bucket's Autoclass configuration.
    @[JSON::Field(key: "autoclass")]
    property autoclass : JSON::Any? = nil

    # The location of the bucket. Object data for objects in the bucket resides in physical storage within this region. Defaults to US. See the [Developer's Guide](https://cloud.google.com/storage/docs/locations) for the authoritative list.
    @[JSON::Field(key: "location")]
    property location : String? = nil

    # The type of the bucket location.
    @[JSON::Field(key: "locationType")]
    property location_type : String? = nil

    # The bucket's logging configuration, which defines the destination bucket and optional name prefix for the current bucket's logs.
    @[JSON::Field(key: "logging")]
    property logging : JSON::Any? = nil

    # The generation of this bucket.
    @[JSON::Field(key: "generation")]
    property generation : String? = nil

    # The metadata generation of this bucket.
    @[JSON::Field(key: "metageneration")]
    property metageneration : String? = nil

    # The name of the bucket.
    @[JSON::Field(key: "name")]
    property name : String? = nil

    # The owner of the bucket. This is always the project team's owner group.
    @[JSON::Field(key: "owner")]
    property owner : JSON::Any? = nil

    # The project number of the project the bucket belongs to.
    @[JSON::Field(key: "projectNumber")]
    property project_number : String? = nil

    # The bucket's retention policy. The retention policy enforces a minimum retention time for all objects contained in the bucket, based on their creation time. Any attempt to overwrite or delete objects younger than the retention period will result in a PERMISSION_DENIED error. An unlocked retention policy can be modified or removed from the bucket via a storage.buckets.update operation. A locked retention policy cannot be removed or shortened in duration for the lifetime of the bucket. Attempting to remove or decrease period of a locked retention policy will result in a PERMISSION_DENIED error.
    @[JSON::Field(key: "retentionPolicy")]
    property retention_policy : JSON::Any? = nil

    # The bucket's object retention config.
    @[JSON::Field(key: "objectRetention")]
    property object_retention : JSON::Any? = nil

    # The Recovery Point Objective (RPO) of this bucket. Set to ASYNC_TURBO to turn on Turbo Replication on a bucket.
    @[JSON::Field(key: "rpo")]
    property rpo : String? = nil

    # The URI of this bucket.
    @[JSON::Field(key: "selfLink")]
    property self_link : String? = nil

    # The bucket's soft delete policy, which defines the period of time that soft-deleted objects will be retained, and cannot be permanently deleted.
    @[JSON::Field(key: "softDeletePolicy")]
    property soft_delete_policy : JSON::Any? = nil

    # The bucket's default storage class, used whenever no storageClass is specified for a newly-created object. This defines how objects in the bucket are stored and determines the SLA and the cost of storage. Values include MULTI_REGIONAL, REGIONAL, STANDARD, NEARLINE, COLDLINE, ARCHIVE, and DURABLE_REDUCED_AVAILABILITY. If this value is not specified when the bucket is created, it will default to STANDARD. For more information, see [Storage Classes](https://cloud.google.com/storage/docs/storage-classes).
    @[JSON::Field(key: "storageClass")]
    property storage_class : String? = nil

    # The creation time of the bucket in RFC 3339 format.
    @[JSON::Field(key: "timeCreated")]
    property time_created : String? = nil

    # The modification time of the bucket in RFC 3339 format.
    @[JSON::Field(key: "updated")]
    property updated : String? = nil

    # The soft delete time of the bucket in RFC 3339 format.
    @[JSON::Field(key: "softDeleteTime")]
    property soft_delete_time : String? = nil

    # The hard delete time of the bucket in RFC 3339 format.
    @[JSON::Field(key: "hardDeleteTime")]
    property hard_delete_time : String? = nil

    # The bucket's versioning configuration.
    @[JSON::Field(key: "versioning")]
    property versioning : JSON::Any? = nil

    # The bucket's website configuration, controlling how the service behaves when accessing bucket contents as a web site. See the [Static Website Examples](https://cloud.google.com/storage/docs/static-website) for more information.
    @[JSON::Field(key: "website")]
    property website : JSON::Any? = nil

    # Reserved for future use.
    @[JSON::Field(key: "satisfiesPZS")]
    property satisfies_pzs : Bool? = nil

    # Reserved for future use.
    @[JSON::Field(key: "satisfiesPZI")]
    property satisfies_pzi : Bool? = nil

    def initialize(
      @acl : Array(BucketAccessControl)? = nil,
      @billing : JSON::Any? = nil,
      @cors : Array(JSON::Any)? = nil,
      @custom_placement_config : JSON::Any? = nil,
      @default_event_based_hold : Bool? = nil,
      @default_object_acl : Array(ObjectAccessControl)? = nil,
      @encryption : JSON::Any? = nil,
      @etag : String? = nil,
      @hierarchical_namespace : JSON::Any? = nil,
      @iam_configuration : JSON::Any? = nil,
      @id : String? = nil,
      @ip_filter : JSON::Any? = nil,
      @kind : String? = nil,
      @labels : Hash(String, String)? = nil,
      @lifecycle : JSON::Any? = nil,
      @autoclass : JSON::Any? = nil,
      @location : String? = nil,
      @location_type : String? = nil,
      @logging : JSON::Any? = nil,
      @generation : String? = nil,
      @metageneration : String? = nil,
      @name : String? = nil,
      @owner : JSON::Any? = nil,
      @project_number : String? = nil,
      @retention_policy : JSON::Any? = nil,
      @object_retention : JSON::Any? = nil,
      @rpo : String? = nil,
      @self_link : String? = nil,
      @soft_delete_policy : JSON::Any? = nil,
      @storage_class : String? = nil,
      @time_created : String? = nil,
      @updated : String? = nil,
      @soft_delete_time : String? = nil,
      @hard_delete_time : String? = nil,
      @versioning : JSON::Any? = nil,
      @website : JSON::Any? = nil,
      @satisfies_pzs : Bool? = nil,
      @satisfies_pzi : Bool? = nil,
    )
    end
  end

  # An access-control entry.
  class BucketAccessControl
    include JSON::Serializable

    # The name of the bucket.
    @[JSON::Field(key: "bucket")]
    property bucket : String? = nil

    # The domain associated with the entity, if any.
    @[JSON::Field(key: "domain")]
    property domain : String? = nil

    # The email address associated with the entity, if any.
    @[JSON::Field(key: "email")]
    property email : String? = nil

    # The entity holding the permission, in one of the following forms:
    # - user-userId
    # - user-email
    # - group-groupId
    # - group-email
    # - domain-domain
    # - project-team-projectId
    # - allUsers
    # - allAuthenticatedUsers Examples:
    # - The user liz@example.com would be user-liz@example.com.
    # - The group example@googlegroups.com would be group-example@googlegroups.com.
    # - To refer to all members of the Google Apps for Business domain example.com, the entity would be domain-example.com.
    @[JSON::Field(key: "entity")]
    property entity : String? = nil

    # The ID for the entity, if any.
    @[JSON::Field(key: "entityId")]
    property entity_id : String? = nil

    # HTTP 1.1 Entity tag for the access-control entry.
    @[JSON::Field(key: "etag")]
    property etag : String? = nil

    # The ID of the access-control entry.
    @[JSON::Field(key: "id")]
    property id : String? = nil

    # The kind of item this is. For bucket access control entries, this is always storage#bucketAccessControl.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    # The project team associated with the entity, if any.
    @[JSON::Field(key: "projectTeam")]
    property project_team : JSON::Any? = nil

    # The access permission for the entity.
    @[JSON::Field(key: "role")]
    property role : String? = nil

    # The link to this access-control entry.
    @[JSON::Field(key: "selfLink")]
    property self_link : String? = nil

    def initialize(
      @bucket : String? = nil,
      @domain : String? = nil,
      @email : String? = nil,
      @entity : String? = nil,
      @entity_id : String? = nil,
      @etag : String? = nil,
      @id : String? = nil,
      @kind : String? = nil,
      @project_team : JSON::Any? = nil,
      @role : String? = nil,
      @self_link : String? = nil,
    )
    end
  end

  # An access-control list.
  class BucketAccessControls
    include JSON::Serializable

    # The list of items.
    @[JSON::Field(key: "items")]
    property items : Array(BucketAccessControl)? = nil

    # The kind of item this is. For lists of bucket access control entries, this is always storage#bucketAccessControls.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    def initialize(
      @items : Array(BucketAccessControl)? = nil,
      @kind : String? = nil,
    )
    end
  end

  # The storage layout configuration of a bucket.
  class BucketStorageLayout
    include JSON::Serializable

    # The name of the bucket.
    @[JSON::Field(key: "bucket")]
    property bucket : String? = nil

    # The bucket's custom placement configuration for Custom Dual Regions.
    @[JSON::Field(key: "customPlacementConfig")]
    property custom_placement_config : JSON::Any? = nil

    # The bucket's hierarchical namespace configuration.
    @[JSON::Field(key: "hierarchicalNamespace")]
    property hierarchical_namespace : JSON::Any? = nil

    # The kind of item this is. For storage layout, this is always storage#storageLayout.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    # The location of the bucket.
    @[JSON::Field(key: "location")]
    property location : String? = nil

    # The type of the bucket location.
    @[JSON::Field(key: "locationType")]
    property location_type : String? = nil

    def initialize(
      @bucket : String? = nil,
      @custom_placement_config : JSON::Any? = nil,
      @hierarchical_namespace : JSON::Any? = nil,
      @kind : String? = nil,
      @location : String? = nil,
      @location_type : String? = nil,
    )
    end
  end

  # A list of buckets.
  class Buckets
    include JSON::Serializable

    # The list of items.
    @[JSON::Field(key: "items")]
    property items : Array(Bucket)? = nil

    # The kind of item this is. For lists of buckets, this is always storage#buckets.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    # The continuation token, used to page through large result sets. Provide this value in a subsequent request to return the next page of results.
    @[JSON::Field(key: "nextPageToken")]
    property next_page_token : String? = nil

    # The list of bucket resource names that could not be reached during the listing operation.
    @[JSON::Field(key: "unreachable")]
    property unreachable : Array(String)? = nil

    def initialize(
      @items : Array(Bucket)? = nil,
      @kind : String? = nil,
      @next_page_token : String? = nil,
      @unreachable : Array(String)? = nil,
    )
    end
  end

  # A bulk restore objects request.
  class BulkRestoreObjectsRequest
    include JSON::Serializable

    # If false (default), the restore will not overwrite live objects with the same name at the destination. This means some deleted objects may be skipped. If true, live objects will be overwritten resulting in a noncurrent object (if versioning is enabled). If versioning is not enabled, overwriting the object will result in a soft-deleted object. In either case, if a noncurrent object already exists with the same name, a live version can be written without issue.
    @[JSON::Field(key: "allowOverwrite")]
    property allow_overwrite : Bool? = nil

    # Restores only the objects that were soft-deleted after this time.
    @[JSON::Field(key: "softDeletedAfterTime")]
    property soft_deleted_after_time : String? = nil

    # Restores only the objects that were soft-deleted before this time.
    @[JSON::Field(key: "softDeletedBeforeTime")]
    property soft_deleted_before_time : String? = nil

    # Restores only the objects matching any of the specified glob(s). If this parameter is not specified, all objects will be restored within the specified time range.
    @[JSON::Field(key: "matchGlobs")]
    property match_globs : Array(String)? = nil

    # If true, copies the source object's ACL; otherwise, uses the bucket's default object ACL. The default is false.
    @[JSON::Field(key: "copySourceAcl")]
    property copy_source_acl : Bool? = nil

    # Restores only the objects that were created after this time.
    @[JSON::Field(key: "createdAfterTime")]
    property created_after_time : String? = nil

    # Restores only the objects that were created before this time.
    @[JSON::Field(key: "createdBeforeTime")]
    property created_before_time : String? = nil

    def initialize(
      @allow_overwrite : Bool? = nil,
      @soft_deleted_after_time : String? = nil,
      @soft_deleted_before_time : String? = nil,
      @match_globs : Array(String)? = nil,
      @copy_source_acl : Bool? = nil,
      @created_after_time : String? = nil,
      @created_before_time : String? = nil,
    )
    end
  end

  # An notification channel used to watch for resource changes.
  class Channel
    include JSON::Serializable

    # The address where notifications are delivered for this channel.
    @[JSON::Field(key: "address")]
    property address : String? = nil

    # Date and time of notification channel expiration, expressed as a Unix timestamp, in milliseconds. Optional.
    @[JSON::Field(key: "expiration")]
    property expiration : String? = nil

    # A UUID or similar unique string that identifies this channel.
    @[JSON::Field(key: "id")]
    property id : String? = nil

    # Identifies this as a notification channel used to watch for changes to a resource, which is "api#channel".
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    # Additional parameters controlling delivery channel behavior. Optional.
    @[JSON::Field(key: "params")]
    property params : Hash(String, String)? = nil

    # A Boolean value to indicate whether payload is wanted. Optional.
    @[JSON::Field(key: "payload")]
    property payload : Bool? = nil

    # An opaque ID that identifies the resource being watched on this channel. Stable across different API versions.
    @[JSON::Field(key: "resourceId")]
    property resource_id : String? = nil

    # A version-specific identifier for the watched resource.
    @[JSON::Field(key: "resourceUri")]
    property resource_uri : String? = nil

    # An arbitrary string delivered to the target address with each notification delivered over this channel. Optional.
    @[JSON::Field(key: "token")]
    property token : String? = nil

    # The type of delivery mechanism used for this channel.
    @[JSON::Field(key: "type")]
    property type_param : String? = nil

    def initialize(
      @address : String? = nil,
      @expiration : String? = nil,
      @id : String? = nil,
      @kind : String? = nil,
      @params : Hash(String, String)? = nil,
      @payload : Bool? = nil,
      @resource_id : String? = nil,
      @resource_uri : String? = nil,
      @token : String? = nil,
      @type_param : String? = nil,
    )
    end
  end

  # A Compose request.
  class ComposeRequest
    include JSON::Serializable

    # Properties of the resulting object.
    @[JSON::Field(key: "destination")]
    property destination : Object? = nil

    # The kind of item this is.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    # The list of source objects that will be concatenated into a single object.
    @[JSON::Field(key: "sourceObjects")]
    property source_objects : Array(JSON::Any)? = nil

    # If true, the source objects will be deleted.
    @[JSON::Field(key: "deleteSourceObjects")]
    property delete_source_objects : Bool? = nil

    def initialize(
      @destination : Object? = nil,
      @kind : String? = nil,
      @source_objects : Array(JSON::Any)? = nil,
      @delete_source_objects : Bool? = nil,
    )
    end
  end

  # Represents an expression text. Example: title: "User account presence" description: "Determines whether the request has a user account" expression: "size(request.user) > 0"
  class Expr
    include JSON::Serializable

    # An optional description of the expression. This is a longer text which describes the expression, e.g. when hovered over it in a UI.
    @[JSON::Field(key: "description")]
    property description : String? = nil

    # Textual representation of an expression in Common Expression Language syntax. The application context of the containing message determines which well-known feature set of CEL is supported.
    @[JSON::Field(key: "expression")]
    property expression : String? = nil

    # An optional string indicating the location of the expression for error reporting, e.g. a file name and a position in the file.
    @[JSON::Field(key: "location")]
    property location : String? = nil

    # An optional title for the expression, i.e. a short string describing its purpose. This can be used e.g. in UIs which allow to enter the expression.
    @[JSON::Field(key: "title")]
    property title : String? = nil

    def initialize(
      @description : String? = nil,
      @expression : String? = nil,
      @location : String? = nil,
      @title : String? = nil,
    )
    end
  end

  # A folder. Only available in buckets with hierarchical namespace enabled.
  class Folder
    include JSON::Serializable

    # The name of the bucket containing this folder.
    @[JSON::Field(key: "bucket")]
    property bucket : String? = nil

    # The ID of the folder, including the bucket name, folder name.
    @[JSON::Field(key: "id")]
    property id : String? = nil

    # The kind of item this is. For folders, this is always storage#folder.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    # The version of the metadata for this folder. Used for preconditions and for detecting changes in metadata.
    @[JSON::Field(key: "metageneration")]
    property metageneration : String? = nil

    # The name of the folder. Required if not specified by URL parameter.
    @[JSON::Field(key: "name")]
    property name : String? = nil

    # The link to this folder.
    @[JSON::Field(key: "selfLink")]
    property self_link : String? = nil

    # The creation time of the folder in RFC 3339 format.
    @[JSON::Field(key: "createTime")]
    property create_time : String? = nil

    # The modification time of the folder metadata in RFC 3339 format.
    @[JSON::Field(key: "updateTime")]
    property update_time : String? = nil

    # Only present if the folder is part of an ongoing rename folder operation. Contains information which can be used to query the operation status.
    @[JSON::Field(key: "pendingRenameInfo")]
    property pending_rename_info : JSON::Any? = nil

    def initialize(
      @bucket : String? = nil,
      @id : String? = nil,
      @kind : String? = nil,
      @metageneration : String? = nil,
      @name : String? = nil,
      @self_link : String? = nil,
      @create_time : String? = nil,
      @update_time : String? = nil,
      @pending_rename_info : JSON::Any? = nil,
    )
    end
  end

  # A list of folders.
  class Folders
    include JSON::Serializable

    # The list of items.
    @[JSON::Field(key: "items")]
    property items : Array(Folder)? = nil

    # The kind of item this is. For lists of folders, this is always storage#folders.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    # The continuation token, used to page through large result sets. Provide this value in a subsequent request to return the next page of results.
    @[JSON::Field(key: "nextPageToken")]
    property next_page_token : String? = nil

    def initialize(
      @items : Array(Folder)? = nil,
      @kind : String? = nil,
      @next_page_token : String? = nil,
    )
    end
  end

  # The response message for storage.buckets.operations.list.
  class GoogleLongrunningListOperationsResponse
    include JSON::Serializable

    # The continuation token, used to page through large result sets. Provide this value in a subsequent request to return the next page of results.
    @[JSON::Field(key: "nextPageToken")]
    property next_page_token : String? = nil

    # A list of operations that matches the specified filter in the request.
    @[JSON::Field(key: "operations")]
    property operations : Array(GoogleLongrunningOperation)? = nil

    # The kind of item this is. For lists of operations, this is always storage#operations.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    def initialize(
      @next_page_token : String? = nil,
      @operations : Array(GoogleLongrunningOperation)? = nil,
      @kind : String? = nil,
    )
    end
  end

  # This resource represents a long-running operation that is the result of a network API call.
  class GoogleLongrunningOperation
    include JSON::Serializable

    # If the value is "false", it means the operation is still in progress. If "true", the operation is completed, and either "error" or "response" is available.
    @[JSON::Field(key: "done")]
    property done : Bool? = nil

    # The error result of the operation in case of failure or cancellation.
    @[JSON::Field(key: "error")]
    property error : GoogleRpcStatus? = nil

    # Service-specific metadata associated with the operation. It typically contains progress information and common metadata such as create time. Some services might not provide such metadata. Any method that returns a long-running operation should document the metadata type, if any.
    @[JSON::Field(key: "metadata")]
    property metadata : Hash(String, JSON::Any)? = nil

    # The server-assigned name, which is only unique within the same service that originally returns it. If you use the default HTTP mapping, the "name" should be a resource name ending with "operations/{operationId}".
    @[JSON::Field(key: "name")]
    property name : String? = nil

    # The normal response of the operation in case of success. If the original method returns no data on success, such as "Delete", the response is google.protobuf.Empty. If the original method is standard Get/Create/Update, the response should be the resource. For other methods, the response should have the type "XxxResponse", where "Xxx" is the original method name. For example, if the original method name is "TakeSnapshot()", the inferred response type is "TakeSnapshotResponse".
    @[JSON::Field(key: "response")]
    property response : Hash(String, JSON::Any)? = nil

    # The link to this long running operation.
    @[JSON::Field(key: "selfLink")]
    property self_link : String? = nil

    # The kind of item this is. For operations, this is always storage#operation.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    def initialize(
      @done : Bool? = nil,
      @error : GoogleRpcStatus? = nil,
      @metadata : Hash(String, JSON::Any)? = nil,
      @name : String? = nil,
      @response : Hash(String, JSON::Any)? = nil,
      @self_link : String? = nil,
      @kind : String? = nil,
    )
    end
  end

  # The "Status" type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc). Each "Status" message contains three pieces of data: error code, error message, and error details. You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors).
  class GoogleRpcStatus
    include JSON::Serializable

    # The status code, which should be an enum value of google.rpc.Code.
    @[JSON::Field(key: "code")]
    property code : Int64? = nil

    # A list of messages that carry the error details. There is a common set of message types for APIs to use.
    @[JSON::Field(key: "details")]
    property details : Array(Hash(String, JSON::Any))? = nil

    # A developer-facing error message, which should be in English.
    @[JSON::Field(key: "message")]
    property message : String? = nil

    def initialize(
      @code : Int64? = nil,
      @details : Array(Hash(String, JSON::Any))? = nil,
      @message : String? = nil,
    )
    end
  end

  # JSON template to produce a JSON-style HMAC Key resource for Create responses.
  class HmacKey
    include JSON::Serializable

    # The kind of item this is. For HMAC keys, this is always storage#hmacKey.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    # Key metadata.
    @[JSON::Field(key: "metadata")]
    property metadata : HmacKeyMetadata? = nil

    # HMAC secret key material.
    @[JSON::Field(key: "secret")]
    property secret : String? = nil

    def initialize(
      @kind : String? = nil,
      @metadata : HmacKeyMetadata? = nil,
      @secret : String? = nil,
    )
    end
  end

  # JSON template to produce a JSON-style HMAC Key metadata resource.
  class HmacKeyMetadata
    include JSON::Serializable

    # The ID of the HMAC Key.
    @[JSON::Field(key: "accessId")]
    property access_id : String? = nil

    # HTTP 1.1 Entity tag for the HMAC key.
    @[JSON::Field(key: "etag")]
    property etag : String? = nil

    # The ID of the HMAC key, including the Project ID and the Access ID.
    @[JSON::Field(key: "id")]
    property id : String? = nil

    # The kind of item this is. For HMAC Key metadata, this is always storage#hmacKeyMetadata.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    # Project ID owning the service account to which the key authenticates.
    @[JSON::Field(key: "projectId")]
    property project_id : String? = nil

    # The link to this resource.
    @[JSON::Field(key: "selfLink")]
    property self_link : String? = nil

    # The email address of the key's associated service account.
    @[JSON::Field(key: "serviceAccountEmail")]
    property service_account_email : String? = nil

    # The state of the key. Can be one of ACTIVE, INACTIVE, or DELETED.
    @[JSON::Field(key: "state")]
    property state : String? = nil

    # The creation time of the HMAC key in RFC 3339 format.
    @[JSON::Field(key: "timeCreated")]
    property time_created : String? = nil

    # The last modification time of the HMAC key metadata in RFC 3339 format.
    @[JSON::Field(key: "updated")]
    property updated : String? = nil

    def initialize(
      @access_id : String? = nil,
      @etag : String? = nil,
      @id : String? = nil,
      @kind : String? = nil,
      @project_id : String? = nil,
      @self_link : String? = nil,
      @service_account_email : String? = nil,
      @state : String? = nil,
      @time_created : String? = nil,
      @updated : String? = nil,
    )
    end
  end

  # A list of hmacKeys.
  class HmacKeysMetadata
    include JSON::Serializable

    # The list of items.
    @[JSON::Field(key: "items")]
    property items : Array(HmacKeyMetadata)? = nil

    # The kind of item this is. For lists of hmacKeys, this is always storage#hmacKeysMetadata.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    # The continuation token, used to page through large result sets. Provide this value in a subsequent request to return the next page of results.
    @[JSON::Field(key: "nextPageToken")]
    property next_page_token : String? = nil

    def initialize(
      @items : Array(HmacKeyMetadata)? = nil,
      @kind : String? = nil,
      @next_page_token : String? = nil,
    )
    end
  end

  # A managed folder.
  class ManagedFolder
    include JSON::Serializable

    # The name of the bucket containing this managed folder.
    @[JSON::Field(key: "bucket")]
    property bucket : String? = nil

    # The ID of the managed folder, including the bucket name and managed folder name.
    @[JSON::Field(key: "id")]
    property id : String? = nil

    # The kind of item this is. For managed folders, this is always storage#managedFolder.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    # The version of the metadata for this managed folder. Used for preconditions and for detecting changes in metadata.
    @[JSON::Field(key: "metageneration")]
    property metageneration : String? = nil

    # The name of the managed folder. Required if not specified by URL parameter.
    @[JSON::Field(key: "name")]
    property name : String? = nil

    # The link to this managed folder.
    @[JSON::Field(key: "selfLink")]
    property self_link : String? = nil

    # The creation time of the managed folder in RFC 3339 format.
    @[JSON::Field(key: "createTime")]
    property create_time : String? = nil

    # The last update time of the managed folder metadata in RFC 3339 format.
    @[JSON::Field(key: "updateTime")]
    property update_time : String? = nil

    # The rapid cache configuration for the managed folder.
    @[JSON::Field(key: "rapidCacheConfig")]
    property rapid_cache_config : RapidCacheConfig? = nil

    def initialize(
      @bucket : String? = nil,
      @id : String? = nil,
      @kind : String? = nil,
      @metageneration : String? = nil,
      @name : String? = nil,
      @self_link : String? = nil,
      @create_time : String? = nil,
      @update_time : String? = nil,
      @rapid_cache_config : RapidCacheConfig? = nil,
    )
    end
  end

  # A list of managed folders.
  class ManagedFolders
    include JSON::Serializable

    # The list of items.
    @[JSON::Field(key: "items")]
    property items : Array(ManagedFolder)? = nil

    # The kind of item this is. For lists of managed folders, this is always storage#managedFolders.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    # The continuation token, used to page through large result sets. Provide this value in a subsequent request to return the next page of results.
    @[JSON::Field(key: "nextPageToken")]
    property next_page_token : String? = nil

    def initialize(
      @items : Array(ManagedFolder)? = nil,
      @kind : String? = nil,
      @next_page_token : String? = nil,
    )
    end
  end

  # A subscription to receive Google PubSub notifications.
  class Notification
    include JSON::Serializable

    # An optional list of additional attributes to attach to each Cloud PubSub message published for this notification subscription.
    @[JSON::Field(key: "custom_attributes")]
    property custom_attributes : Hash(String, String)? = nil

    # HTTP 1.1 Entity tag for this subscription notification.
    @[JSON::Field(key: "etag")]
    property etag : String? = nil

    # If present, only send notifications about listed event types. If empty, sent notifications for all event types.
    @[JSON::Field(key: "event_types")]
    property event_types : Array(String)? = nil

    # The ID of the notification.
    @[JSON::Field(key: "id")]
    property id : String? = nil

    # The kind of item this is. For notifications, this is always storage#notification.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    # If present, only apply this notification configuration to object names that begin with this prefix.
    @[JSON::Field(key: "object_name_prefix")]
    property object_name_prefix : String? = nil

    # The desired content of the Payload.
    @[JSON::Field(key: "payload_format")]
    property payload_format : String? = nil

    # The canonical URL of this notification.
    @[JSON::Field(key: "selfLink")]
    property self_link : String? = nil

    # The Cloud PubSub topic to which this subscription publishes. Formatted as: '//pubsub.googleapis.com/projects/{project-identifier}/topics/{my-topic}'
    @[JSON::Field(key: "topic")]
    property topic : String? = nil

    def initialize(
      @custom_attributes : Hash(String, String)? = nil,
      @etag : String? = nil,
      @event_types : Array(String)? = nil,
      @id : String? = nil,
      @kind : String? = nil,
      @object_name_prefix : String? = nil,
      @payload_format : String? = nil,
      @self_link : String? = nil,
      @topic : String? = nil,
    )
    end
  end

  # A list of notification subscriptions.
  class Notifications
    include JSON::Serializable

    # The list of items.
    @[JSON::Field(key: "items")]
    property items : Array(Notification)? = nil

    # The kind of item this is. For lists of notifications, this is always storage#notifications.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    def initialize(
      @items : Array(Notification)? = nil,
      @kind : String? = nil,
    )
    end
  end

  # An object.
  class Object
    include JSON::Serializable

    # Access controls on the object.
    @[JSON::Field(key: "acl")]
    property acl : Array(ObjectAccessControl)? = nil

    # The name of the bucket containing this object.
    @[JSON::Field(key: "bucket")]
    property bucket : String? = nil

    # Cache-Control directive for the object data. If omitted, and the object is accessible to all anonymous users, the default will be public, max-age=3600.
    @[JSON::Field(key: "cacheControl")]
    property cache_control : String? = nil

    # Number of underlying components that make up this object. Components are accumulated by compose operations.
    @[JSON::Field(key: "componentCount")]
    property component_count : Int64? = nil

    # Content-Disposition of the object data.
    @[JSON::Field(key: "contentDisposition")]
    property content_disposition : String? = nil

    # Content-Encoding of the object data.
    @[JSON::Field(key: "contentEncoding")]
    property content_encoding : String? = nil

    # Content-Language of the object data.
    @[JSON::Field(key: "contentLanguage")]
    property content_language : String? = nil

    # Content-Type of the object data. If an object is stored without a Content-Type, it is served as application/octet-stream.
    @[JSON::Field(key: "contentType")]
    property content_type : String? = nil

    # CRC32c checksum, as described in RFC 4960, Appendix B; encoded using base64 in big-endian byte order. For more information about using the CRC32c checksum, see [Data Validation and Change Detection](https://cloud.google.com/storage/docs/data-validation).
    @[JSON::Field(key: "crc32c")]
    property crc32c : String? = nil

    # A timestamp in RFC 3339 format specified by the user for an object.
    @[JSON::Field(key: "customTime")]
    property custom_time : String? = nil

    # Metadata of customer-supplied encryption key, if the object is encrypted by such a key.
    @[JSON::Field(key: "customerEncryption")]
    property customer_encryption : JSON::Any? = nil

    # HTTP 1.1 Entity tag for the object.
    @[JSON::Field(key: "etag")]
    property etag : String? = nil

    # Whether an object is under event-based hold. Event-based hold is a way to retain objects until an event occurs, which is signified by the hold's release (i.e. this value is set to false). After being released (set to false), such objects will be subject to bucket-level retention (if any). One sample use case of this flag is for banks to hold loan documents for at least 3 years after loan is paid in full. Here, bucket-level retention is 3 years and the event is the loan being paid in full. In this example, these objects will be held intact for any number of years until the event has occurred (event-based hold on the object is released) and then 3 more years after that. That means retention duration of the objects begins from the moment event-based hold transitioned from true to false.
    @[JSON::Field(key: "eventBasedHold")]
    property event_based_hold : Bool? = nil

    # The content generation of this object. Used for object versioning.
    @[JSON::Field(key: "generation")]
    property generation : String? = nil

    # The ID of the object, including the bucket name, object name, and generation number.
    @[JSON::Field(key: "id")]
    property id : String? = nil

    # The kind of item this is. For objects, this is always storage#object.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    # Not currently supported. Specifying the parameter causes the request to fail with status code 400 - Bad Request.
    @[JSON::Field(key: "kmsKeyName")]
    property kms_key_name : String? = nil

    # MD5 hash of the data; encoded using base64. For more information about using the MD5 hash, see [Data Validation and Change Detection](https://cloud.google.com/storage/docs/data-validation).
    @[JSON::Field(key: "md5Hash")]
    property md5_hash : String? = nil

    # Media download link.
    @[JSON::Field(key: "mediaLink")]
    property media_link : String? = nil

    # User-provided metadata, in key/value pairs.
    @[JSON::Field(key: "metadata")]
    property metadata : Hash(String, String)? = nil

    # User-defined or system-defined object contexts. Each object context is a key-payload pair, where the key provides the identification and the payload holds the associated value and additional metadata.
    @[JSON::Field(key: "contexts")]
    property contexts : JSON::Any? = nil

    # Restore token used to differentiate deleted objects with the same name and generation. This field is only returned for deleted objects in hierarchical namespace buckets.
    @[JSON::Field(key: "restoreToken")]
    property restore_token : String? = nil

    # The version of the metadata for this object at this generation. Used for preconditions and for detecting changes in metadata. A metageneration number is only meaningful in the context of a particular generation of a particular object.
    @[JSON::Field(key: "metageneration")]
    property metageneration : String? = nil

    # The name of the object. Required if not specified by URL parameter.
    @[JSON::Field(key: "name")]
    property name : String? = nil

    # The owner of the object. This will always be the uploader of the object.
    @[JSON::Field(key: "owner")]
    property owner : JSON::Any? = nil

    # A server-determined value that specifies the earliest time that the object's retention period expires. This value is in RFC 3339 format. Note 1: This field is not provided for objects with an active event-based hold, since retention expiration is unknown until the hold is removed. Note 2: This value can be provided even when temporary hold is set (so that the user can reason about policy without having to first unset the temporary hold).
    @[JSON::Field(key: "retentionExpirationTime")]
    property retention_expiration_time : String? = nil

    # A collection of object level retention parameters.
    @[JSON::Field(key: "retention")]
    property retention : JSON::Any? = nil

    # The link to this object.
    @[JSON::Field(key: "selfLink")]
    property self_link : String? = nil

    # Content-Length of the data in bytes.
    @[JSON::Field(key: "size")]
    property size : String? = nil

    # Storage class of the object.
    @[JSON::Field(key: "storageClass")]
    property storage_class : String? = nil

    # Whether an object is under temporary hold. While this flag is set to true, the object is protected against deletion and overwrites. A common use case of this flag is regulatory investigations where objects need to be retained while the investigation is ongoing. Note that unlike event-based hold, temporary hold does not impact retention expiration time of an object.
    @[JSON::Field(key: "temporaryHold")]
    property temporary_hold : Bool? = nil

    # The creation time of the object in RFC 3339 format.
    @[JSON::Field(key: "timeCreated")]
    property time_created : String? = nil

    # The time at which the object became noncurrent in RFC 3339 format. Will be returned if and only if this version of the object has been deleted.
    @[JSON::Field(key: "timeDeleted")]
    property time_deleted : String? = nil

    # The time when the object was finalized.
    @[JSON::Field(key: "timeFinalized")]
    property time_finalized : String? = nil

    # The time at which the object became soft-deleted in RFC 3339 format.
    @[JSON::Field(key: "softDeleteTime")]
    property soft_delete_time : String? = nil

    # This is the time (in the future) when the soft-deleted object will no longer be restorable. It is equal to the soft delete time plus the current soft delete retention duration of the bucket.
    @[JSON::Field(key: "hardDeleteTime")]
    property hard_delete_time : String? = nil

    # The time at which the object's storage class was last changed. When the object is initially created, it will be set to timeCreated.
    @[JSON::Field(key: "timeStorageClassUpdated")]
    property time_storage_class_updated : String? = nil

    # The modification time of the object metadata in RFC 3339 format. Set initially to object creation time and then updated whenever any metadata of the object changes. This includes changes made by a requester, such as modifying custom metadata, as well as changes made by Cloud Storage on behalf of a requester, such as changing the storage class based on an Object Lifecycle Configuration.
    @[JSON::Field(key: "updated")]
    property updated : String? = nil

    def initialize(
      @acl : Array(ObjectAccessControl)? = nil,
      @bucket : String? = nil,
      @cache_control : String? = nil,
      @component_count : Int64? = nil,
      @content_disposition : String? = nil,
      @content_encoding : String? = nil,
      @content_language : String? = nil,
      @content_type : String? = nil,
      @crc32c : String? = nil,
      @custom_time : String? = nil,
      @customer_encryption : JSON::Any? = nil,
      @etag : String? = nil,
      @event_based_hold : Bool? = nil,
      @generation : String? = nil,
      @id : String? = nil,
      @kind : String? = nil,
      @kms_key_name : String? = nil,
      @md5_hash : String? = nil,
      @media_link : String? = nil,
      @metadata : Hash(String, String)? = nil,
      @contexts : JSON::Any? = nil,
      @restore_token : String? = nil,
      @metageneration : String? = nil,
      @name : String? = nil,
      @owner : JSON::Any? = nil,
      @retention_expiration_time : String? = nil,
      @retention : JSON::Any? = nil,
      @self_link : String? = nil,
      @size : String? = nil,
      @storage_class : String? = nil,
      @temporary_hold : Bool? = nil,
      @time_created : String? = nil,
      @time_deleted : String? = nil,
      @time_finalized : String? = nil,
      @soft_delete_time : String? = nil,
      @hard_delete_time : String? = nil,
      @time_storage_class_updated : String? = nil,
      @updated : String? = nil,
    )
    end
  end

  # An access-control entry.
  class ObjectAccessControl
    include JSON::Serializable

    # The name of the bucket.
    @[JSON::Field(key: "bucket")]
    property bucket : String? = nil

    # The domain associated with the entity, if any.
    @[JSON::Field(key: "domain")]
    property domain : String? = nil

    # The email address associated with the entity, if any.
    @[JSON::Field(key: "email")]
    property email : String? = nil

    # The entity holding the permission, in one of the following forms:
    # - user-userId
    # - user-email
    # - group-groupId
    # - group-email
    # - domain-domain
    # - project-team-projectId
    # - allUsers
    # - allAuthenticatedUsers Examples:
    # - The user liz@example.com would be user-liz@example.com.
    # - The group example@googlegroups.com would be group-example@googlegroups.com.
    # - To refer to all members of the Google Apps for Business domain example.com, the entity would be domain-example.com.
    @[JSON::Field(key: "entity")]
    property entity : String? = nil

    # The ID for the entity, if any.
    @[JSON::Field(key: "entityId")]
    property entity_id : String? = nil

    # HTTP 1.1 Entity tag for the access-control entry.
    @[JSON::Field(key: "etag")]
    property etag : String? = nil

    # The content generation of the object, if applied to an object.
    @[JSON::Field(key: "generation")]
    property generation : String? = nil

    # The ID of the access-control entry.
    @[JSON::Field(key: "id")]
    property id : String? = nil

    # The kind of item this is. For object access control entries, this is always storage#objectAccessControl.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    # The name of the object, if applied to an object.
    @[JSON::Field(key: "object")]
    property object : String? = nil

    # The project team associated with the entity, if any.
    @[JSON::Field(key: "projectTeam")]
    property project_team : JSON::Any? = nil

    # The access permission for the entity.
    @[JSON::Field(key: "role")]
    property role : String? = nil

    # The link to this access-control entry.
    @[JSON::Field(key: "selfLink")]
    property self_link : String? = nil

    def initialize(
      @bucket : String? = nil,
      @domain : String? = nil,
      @email : String? = nil,
      @entity : String? = nil,
      @entity_id : String? = nil,
      @etag : String? = nil,
      @generation : String? = nil,
      @id : String? = nil,
      @kind : String? = nil,
      @object : String? = nil,
      @project_team : JSON::Any? = nil,
      @role : String? = nil,
      @self_link : String? = nil,
    )
    end
  end

  # An access-control list.
  class ObjectAccessControls
    include JSON::Serializable

    # The list of items.
    @[JSON::Field(key: "items")]
    property items : Array(ObjectAccessControl)? = nil

    # The kind of item this is. For lists of object access control entries, this is always storage#objectAccessControls.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    def initialize(
      @items : Array(ObjectAccessControl)? = nil,
      @kind : String? = nil,
    )
    end
  end

  # The payload of a single user-defined object context.
  class ObjectCustomContextPayload
    include JSON::Serializable

    # The value of the object context.
    @[JSON::Field(key: "value")]
    property value : String? = nil

    # The time at which the object context was created in RFC 3339 format.
    @[JSON::Field(key: "createTime")]
    property create_time : String? = nil

    # The time at which the object context was last updated in RFC 3339 format.
    @[JSON::Field(key: "updateTime")]
    property update_time : String? = nil

    # The type URL of the object context's extended data.
    @[JSON::Field(key: "extendedDataTypeUrl")]
    property extended_data_type_url : String? = nil

    def initialize(
      @value : String? = nil,
      @create_time : String? = nil,
      @update_time : String? = nil,
      @extended_data_type_url : String? = nil,
    )
    end
  end

  # A full representation of an object context.
  class ObjectFullContext
    include JSON::Serializable

    # The kind of item this is. For ObjectFullContext, this is always storage#objectFullContext.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    # The type of the object context.
    @[JSON::Field(key: "type")]
    property type_param : String? = nil

    # The key of the object context.
    @[JSON::Field(key: "key")]
    property key : String? = nil

    # The value of the object context.
    @[JSON::Field(key: "value")]
    property value : String? = nil

    # The time at which the object context was created. This value is in RFC 3339 format.
    @[JSON::Field(key: "createTime")]
    property create_time : String? = nil

    # The time at which the object context was last updated. This value is in RFC 3339 format.
    @[JSON::Field(key: "updateTime")]
    property update_time : String? = nil

    # The extended data of the object context.
    @[JSON::Field(key: "extendedData")]
    property extended_data : Hash(String, JSON::Any)? = nil

    def initialize(
      @kind : String? = nil,
      @type_param : String? = nil,
      @key : String? = nil,
      @value : String? = nil,
      @create_time : String? = nil,
      @update_time : String? = nil,
      @extended_data : Hash(String, JSON::Any)? = nil,
    )
    end
  end

  # A list of objects.
  class Objects
    include JSON::Serializable

    # The list of items.
    @[JSON::Field(key: "items")]
    property items : Array(Object)? = nil

    # The kind of item this is. For lists of objects, this is always storage#objects.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    # The continuation token, used to page through large result sets. Provide this value in a subsequent request to return the next page of results.
    @[JSON::Field(key: "nextPageToken")]
    property next_page_token : String? = nil

    # The list of prefixes of objects matching-but-not-listed up to and including the requested delimiter.
    @[JSON::Field(key: "prefixes")]
    property prefixes : Array(String)? = nil

    def initialize(
      @items : Array(Object)? = nil,
      @kind : String? = nil,
      @next_page_token : String? = nil,
      @prefixes : Array(String)? = nil,
    )
    end
  end

  # A bucket/object/managedFolder IAM policy.
  class Policy
    include JSON::Serializable

    # An association between a role, which comes with a set of permissions, and members who may assume that role.
    @[JSON::Field(key: "bindings")]
    property bindings : Array(JSON::Any)? = nil

    # HTTP 1.1  Entity tag for the policy.
    @[JSON::Field(key: "etag")]
    property etag : String? = nil

    # The kind of item this is. For policies, this is always storage#policy. This field is ignored on input.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    # The ID of the resource to which this policy belongs. Will be of the form projects/_/buckets/bucket for buckets, projects/_/buckets/bucket/objects/object for objects, and projects/_/buckets/bucket/managedFolders/managedFolder. A specific generation may be specified by appending #generationNumber to the end of the object name, e.g. projects/_/buckets/my-bucket/objects/data.txt#17. The current generation can be denoted with #0. This field is ignored on input.
    @[JSON::Field(key: "resourceId")]
    property resource_id : String? = nil

    # The IAM policy format version.
    @[JSON::Field(key: "version")]
    property version : Int64? = nil

    def initialize(
      @bindings : Array(JSON::Any)? = nil,
      @etag : String? = nil,
      @kind : String? = nil,
      @resource_id : String? = nil,
      @version : Int64? = nil,
    )
    end
  end

  # A Rapid Cache instance.
  class RapidCache
    include JSON::Serializable

    # The kind of item this is. For Rapid Cache, this is always storage#rapidCache.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    # The ID of the resource, including the project number, bucket name and rapid cache ID.
    @[JSON::Field(key: "id")]
    property id : String? = nil

    # The link to this cache instance.
    @[JSON::Field(key: "selfLink")]
    property self_link : String? = nil

    # The name of the bucket containing this cache instance.
    @[JSON::Field(key: "bucket")]
    property bucket : String? = nil

    # The ID of the Rapid cache instance.
    @[JSON::Field(key: "rapidCacheId")]
    property rapid_cache_id : String? = nil

    # The zone in which the cache instance is running. For example, us-central1-a.
    @[JSON::Field(key: "zone")]
    property zone : String? = nil

    # The current state of the cache instance.
    @[JSON::Field(key: "state")]
    property state : String? = nil

    # The creation time of the cache instance in RFC 3339 format.
    @[JSON::Field(key: "createTime")]
    property create_time : String? = nil

    # The modification time of the cache instance metadata in RFC 3339 format.
    @[JSON::Field(key: "updateTime")]
    property update_time : String? = nil

    # The TTL of all cache entries in whole seconds. e.g., "7200s".
    @[JSON::Field(key: "ttl")]
    property ttl : String? = nil

    # The cache-level entry admission policy.
    @[JSON::Field(key: "admissionPolicy")]
    property admission_policy : String? = nil

    # True if the cache instance has an active Update long-running operation.
    @[JSON::Field(key: "pendingUpdate")]
    property pending_update : Bool? = nil

    # Specifies whether objects are ingested into the cache upon write.
    @[JSON::Field(key: "ingestOnWrite")]
    property ingest_on_write : Bool? = nil

    # The type of Rapid Cache this represents. Valid values include: "rapid-cache" and "rapid-cache-ultra".
    @[JSON::Field(key: "cacheType")]
    property cache_type : String? = nil

    def initialize(
      @kind : String? = nil,
      @id : String? = nil,
      @self_link : String? = nil,
      @bucket : String? = nil,
      @rapid_cache_id : String? = nil,
      @zone : String? = nil,
      @state : String? = nil,
      @create_time : String? = nil,
      @update_time : String? = nil,
      @ttl : String? = nil,
      @admission_policy : String? = nil,
      @pending_update : Bool? = nil,
      @ingest_on_write : Bool? = nil,
      @cache_type : String? = nil,
    )
    end
  end

  # Configuration options for the rapid cache of a managed folder.
  class RapidCacheConfig
    include JSON::Serializable

    # A map of rapid cache IDs to the corresponding `RapidCachePolicy` configurations for a managed folder.
    @[JSON::Field(key: "policies")]
    property policies : Hash(String, RapidCachePolicy)? = nil

    def initialize(
      @policies : Hash(String, RapidCachePolicy)? = nil,
    )
    end
  end

  # The rapid cache policy configuration for a managed folder.
  class RapidCachePolicy
    include JSON::Serializable

    # The unique identifier of the rapid cache.
    @[JSON::Field(key: "rapidCacheId")]
    property rapid_cache_id : String? = nil

    # The ingest-on-write policy for objects in the managed folder. When set to `enabled`, objects are automatically ingested into the cache when they are written to the managed folder.
    @[JSON::Field(key: "ingestOnWrite")]
    property ingest_on_write : String? = nil

    def initialize(
      @rapid_cache_id : String? = nil,
      @ingest_on_write : String? = nil,
    )
    end
  end

  # A list of Rapid Caches.
  class RapidCaches
    include JSON::Serializable

    # The kind of item this is. For lists of Rapid Caches, this is always storage#rapidCaches.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    # The continuation token, used to page through large result sets. Provide this value in a subsequent request to return the next page of results.
    @[JSON::Field(key: "nextPageToken")]
    property next_page_token : String? = nil

    # The list of items.
    @[JSON::Field(key: "items")]
    property items : Array(RapidCache)? = nil

    def initialize(
      @kind : String? = nil,
      @next_page_token : String? = nil,
      @items : Array(RapidCache)? = nil,
    )
    end
  end

  # A Relocate Bucket request.
  class RelocateBucketRequest
    include JSON::Serializable

    # The new location the bucket will be relocated to.
    @[JSON::Field(key: "destinationLocation")]
    property destination_location : String? = nil

    # The bucket's new custom placement configuration if relocating to a Custom Dual Region.
    @[JSON::Field(key: "destinationCustomPlacementConfig")]
    property destination_custom_placement_config : JSON::Any? = nil

    # If true, validate the operation, but do not actually relocate the bucket.
    @[JSON::Field(key: "validateOnly")]
    property validate_only : Bool? = nil

    # Resource name of a Cloud KMS key, of the form projects/my-project/locations/global/keyRings/my-kr/cryptoKeys/my-key. If set, is used to encrypt all objects in the destination bucket.
    @[JSON::Field(key: "destinationKmsKeyName")]
    property destination_kms_key_name : String? = nil

    def initialize(
      @destination_location : String? = nil,
      @destination_custom_placement_config : JSON::Any? = nil,
      @validate_only : Bool? = nil,
      @destination_kms_key_name : String? = nil,
    )
    end
  end

  # A rewrite response.
  class RewriteResponse
    include JSON::Serializable

    # true if the copy is finished; otherwise, false if the copy is in progress. This property is always present in the response.
    @[JSON::Field(key: "done")]
    property done : Bool? = nil

    # The kind of item this is.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    # The total size of the object being copied in bytes. This property is always present in the response.
    @[JSON::Field(key: "objectSize")]
    property object_size : String? = nil

    # A resource containing the metadata for the copied-to object. This property is present in the response only when copying completes.
    @[JSON::Field(key: "resource")]
    property resource : Object? = nil

    # A token to use in subsequent requests to continue copying data. This token is present in the response only when there is more data to copy.
    @[JSON::Field(key: "rewriteToken")]
    property rewrite_token : String? = nil

    # The total bytes written so far, which can be used to provide a waiting user with a progress indicator. This property is always present in the response.
    @[JSON::Field(key: "totalBytesRewritten")]
    property total_bytes_rewritten : String? = nil

    def initialize(
      @done : Bool? = nil,
      @kind : String? = nil,
      @object_size : String? = nil,
      @resource : Object? = nil,
      @rewrite_token : String? = nil,
      @total_bytes_rewritten : String? = nil,
    )
    end
  end

  # A subscription to receive Google PubSub notifications.
  class ServiceAccount
    include JSON::Serializable

    # The ID of the notification.
    @[JSON::Field(key: "email_address")]
    property email_address : String? = nil

    # The kind of item this is. For notifications, this is always storage#notification.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    def initialize(
      @email_address : String? = nil,
      @kind : String? = nil,
    )
    end
  end

  # A storage.(buckets|objects|managedFolders).testIamPermissions response.
  class TestIamPermissionsResponse
    include JSON::Serializable

    # The kind of item this is.
    @[JSON::Field(key: "kind")]
    property kind : String? = nil

    # The permissions held by the caller. Permissions are always of the format storage.resource.capability, where resource is one of buckets, objects, or managedFolders. The supported permissions are as follows:
    # - storage.buckets.delete - Delete bucket.
    # - storage.buckets.get - Read bucket metadata.
    # - storage.buckets.getIamPolicy - Read bucket IAM policy.
    # - storage.buckets.create - Create bucket.
    # - storage.buckets.list - List buckets.
    # - storage.buckets.setIamPolicy - Update bucket IAM policy.
    # - storage.buckets.update - Update bucket metadata.
    # - storage.objects.delete - Delete object.
    # - storage.objects.get - Read object data and metadata.
    # - storage.objects.getIamPolicy - Read object IAM policy.
    # - storage.objects.create - Create object.
    # - storage.objects.list - List objects.
    # - storage.objects.setIamPolicy - Update object IAM policy.
    # - storage.objects.update - Update object metadata.
    # - storage.managedFolders.delete - Delete managed folder.
    # - storage.managedFolders.get - Read managed folder metadata.
    # - storage.managedFolders.getIamPolicy - Read managed folder IAM policy.
    # - storage.managedFolders.create - Create managed folder.
    # - storage.managedFolders.list - List managed folders.
    # - storage.managedFolders.setIamPolicy - Update managed folder IAM policy.
    @[JSON::Field(key: "permissions")]
    property permissions : Array(String)? = nil

    def initialize(
      @kind : String? = nil,
      @permissions : Array(String)? = nil,
    )
    end
  end
end
