# Generated by Google APIs Discovery Generator for storage (v1)
# Do not edit directly.

require "./types"
require "./client"
require "./anywhere_caches_service"
require "./rapid_caches_service"
require "./bucket_access_controls_service"
require "./buckets_service"
require "./operations_service"
require "./channels_service"
require "./default_object_access_controls_service"
require "./folders_service"
require "./managed_folders_service"
require "./notifications_service"
require "./object_access_controls_service"
require "./objects_service"
require "./projects_hmac_keys_service"
require "./projects_service_account_service"

module GoogleApis::Storage::V1
end
