# Generated by Google APIs Discovery Generator for dns (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Dns::V1
  class ChangesService < GoogleApis::Service
    # Enumerates Changes to a ResourceRecordSet collection.
    def list(
      project : String,
      managed_zone : String,
      max_results : Int64? = nil,
      page_token : String? = nil,
      sort_by : String? = nil,
      sort_order : String? = nil,
    ) : ChangesListResponse
      req_path = "dns/v1/projects/{project}/managedZones/{managedZone}/changes"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{managedZone}", URI.encode_path_segment(managed_zone.to_s))
      req_path = req_path.gsub("{+managedZone}", managed_zone.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["maxResults"] = max_results unless max_results.nil?
      params["pageToken"] = page_token unless page_token.nil?
      params["sortBy"] = sort_by unless sort_by.nil?
      params["sortOrder"] = sort_order unless sort_order.nil?

      @client.execute(
        type: ChangesListResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Fetches the representation of an existing Change.
    def get(
      project : String,
      managed_zone : String,
      change_id : String,
      client_operation_id : String? = nil,
    ) : Change
      req_path = "dns/v1/projects/{project}/managedZones/{managedZone}/changes/{changeId}"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{managedZone}", URI.encode_path_segment(managed_zone.to_s))
      req_path = req_path.gsub("{+managedZone}", managed_zone.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{changeId}", URI.encode_path_segment(change_id.to_s))
      req_path = req_path.gsub("{+changeId}", change_id.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?

      @client.execute(
        type: Change,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Atomically updates the ResourceRecordSet collection. Note: While `dns.changes.create` is the baseline permission required to invoke this method, additional permissions are checked depending on the specific additions or deletions contained in the payload.
    def create(
      project : String,
      managed_zone : String,
      body : Change? = nil,
      client_operation_id : String? = nil,
    ) : Change
      req_path = "dns/v1/projects/{project}/managedZones/{managedZone}/changes"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{managedZone}", URI.encode_path_segment(managed_zone.to_s))
      req_path = req_path.gsub("{+managedZone}", managed_zone.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?

      @client.execute(
        type: Change,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end
  end
end
