# Generated by Google APIs Discovery Generator for dns (v1)
# Do not edit directly.

require "../../client"
require "../../auth"
require "./changes_service"
require "./projects_service"
require "./resource_record_sets_service"
require "./policies_service"
require "./dns_keys_service"
require "./response_policy_rules_service"
require "./managed_zone_operations_service"
require "./managed_zones_service"
require "./response_policies_service"

module GoogleApis::Dns::V1
  # Client for the Cloud DNS API API (v1).
  class Client
    DEFAULT_BASE_URL = "https://dns.googleapis.com/"

    getter client : GoogleApis::Client
    getter changes : ChangesService
    getter projects : ProjectsService
    getter resource_record_sets : ResourceRecordSetsService
    getter policies : PoliciesService
    getter dns_keys : DnsKeysService
    getter response_policy_rules : ResponsePolicyRulesService
    getter managed_zone_operations : ManagedZoneOperationsService
    getter managed_zones : ManagedZonesService
    getter response_policies : ResponsePoliciesService

    def initialize(
      credentials : GoogleApis::Auth::Credentials,
      base_url : String = DEFAULT_BASE_URL,
    )
      @client = GoogleApis::Client.new(credentials, base_url)
      @changes = ChangesService.new(@client)
      @projects = ProjectsService.new(@client)
      @resource_record_sets = ResourceRecordSetsService.new(@client)
      @policies = PoliciesService.new(@client)
      @dns_keys = DnsKeysService.new(@client)
      @response_policy_rules = ResponsePolicyRulesService.new(@client)
      @managed_zone_operations = ManagedZoneOperationsService.new(@client)
      @managed_zones = ManagedZonesService.new(@client)
      @response_policies = ResponsePoliciesService.new(@client)
    end
  end
end
