# Generated by Google APIs Discovery Generator for dns (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Dns::V1
  class DnsKeysService < GoogleApis::Service
    # Enumerates DnsKeys to a ResourceRecordSet collection.
    def list(
      project : String,
      managed_zone : String,
      digest_type : String? = nil,
      max_results : Int64? = nil,
      page_token : String? = nil,
    ) : DnsKeysListResponse
      req_path = "dns/v1/projects/{project}/managedZones/{managedZone}/dnsKeys"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{managedZone}", URI.encode_path_segment(managed_zone.to_s))
      req_path = req_path.gsub("{+managedZone}", managed_zone.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["digestType"] = digest_type unless digest_type.nil?
      params["maxResults"] = max_results unless max_results.nil?
      params["pageToken"] = page_token unless page_token.nil?

      @client.execute(
        type: DnsKeysListResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Fetches the representation of an existing DnsKey.
    def get(
      project : String,
      managed_zone : String,
      dns_key_id : String,
      client_operation_id : String? = nil,
      digest_type : String? = nil,
    ) : DnsKey
      req_path = "dns/v1/projects/{project}/managedZones/{managedZone}/dnsKeys/{dnsKeyId}"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{managedZone}", URI.encode_path_segment(managed_zone.to_s))
      req_path = req_path.gsub("{+managedZone}", managed_zone.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{dnsKeyId}", URI.encode_path_segment(dns_key_id.to_s))
      req_path = req_path.gsub("{+dnsKeyId}", dns_key_id.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?
      params["digestType"] = digest_type unless digest_type.nil?

      @client.execute(
        type: DnsKey,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end
  end
end
