# Generated by Google APIs Discovery Generator for dns (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Dns::V1
  class ManagedZoneOperationsService < GoogleApis::Service
    # Enumerates Operations for the given ManagedZone.
    def list(
      project : String,
      managed_zone : String,
      max_results : Int64? = nil,
      page_token : String? = nil,
      sort_by : String? = nil,
    ) : ManagedZoneOperationsListResponse
      req_path = "dns/v1/projects/{project}/managedZones/{managedZone}/operations"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{managedZone}", URI.encode_path_segment(managed_zone.to_s))
      req_path = req_path.gsub("{+managedZone}", managed_zone.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["maxResults"] = max_results unless max_results.nil?
      params["pageToken"] = page_token unless page_token.nil?
      params["sortBy"] = sort_by unless sort_by.nil?

      @client.execute(
        type: ManagedZoneOperationsListResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Fetches the representation of an existing Operation.
    def get(
      project : String,
      managed_zone : String,
      operation : String,
      client_operation_id : String? = nil,
    ) : Operation
      req_path = "dns/v1/projects/{project}/managedZones/{managedZone}/operations/{operation}"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{managedZone}", URI.encode_path_segment(managed_zone.to_s))
      req_path = req_path.gsub("{+managedZone}", managed_zone.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{operation}", URI.encode_path_segment(operation.to_s))
      req_path = req_path.gsub("{+operation}", operation.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?

      @client.execute(
        type: Operation,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end
  end
end
