# Generated by Google APIs Discovery Generator for dns (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Dns::V1
  class ManagedZonesService < GoogleApis::Service
    # Updates an existing ManagedZone.
    def update(
      project : String,
      managed_zone : String,
      body : ManagedZone? = nil,
      client_operation_id : String? = nil,
    ) : Operation
      req_path = "dns/v1/projects/{project}/managedZones/{managedZone}"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{managedZone}", URI.encode_path_segment(managed_zone.to_s))
      req_path = req_path.gsub("{+managedZone}", managed_zone.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?

      @client.execute(
        type: Operation,
        http_method: "PUT",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.
    def get_iam_policy(
      resource : String,
      body : GoogleIamV1GetIamPolicyRequest? = nil,
    ) : GoogleIamV1Policy
      req_path = "dns/v1/{+resource}:getIamPolicy"
      req_path = req_path.gsub("{resource}", URI.encode_path_segment(resource.to_s))
      req_path = req_path.gsub("{+resource}", resource.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleIamV1Policy,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Applies a partial update to an existing ManagedZone.
    def patch(
      project : String,
      managed_zone : String,
      body : ManagedZone? = nil,
      client_operation_id : String? = nil,
    ) : Operation
      req_path = "dns/v1/projects/{project}/managedZones/{managedZone}"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{managedZone}", URI.encode_path_segment(managed_zone.to_s))
      req_path = req_path.gsub("{+managedZone}", managed_zone.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?

      @client.execute(
        type: Operation,
        http_method: "PATCH",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Returns permissions that a caller has on the specified resource. If the resource does not exist, this returns an empty set of permissions, not a `NOT_FOUND` error. Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may "fail open" without warning.
    def test_iam_permissions(
      resource : String,
      body : GoogleIamV1TestIamPermissionsRequest? = nil,
    ) : GoogleIamV1TestIamPermissionsResponse
      req_path = "dns/v1/{+resource}:testIamPermissions"
      req_path = req_path.gsub("{resource}", URI.encode_path_segment(resource.to_s))
      req_path = req_path.gsub("{+resource}", resource.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleIamV1TestIamPermissionsResponse,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Enumerates ManagedZones that have been created but not yet deleted.
    def list(
      project : String,
      dns_name : String? = nil,
      max_results : Int64? = nil,
      page_token : String? = nil,
    ) : ManagedZonesListResponse
      req_path = "dns/v1/projects/{project}/managedZones"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["dnsName"] = dns_name unless dns_name.nil?
      params["maxResults"] = max_results unless max_results.nil?
      params["pageToken"] = page_token unless page_token.nil?

      @client.execute(
        type: ManagedZonesListResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Fetches the representation of an existing ManagedZone.
    def get(
      project : String,
      managed_zone : String,
      client_operation_id : String? = nil,
    ) : ManagedZone
      req_path = "dns/v1/projects/{project}/managedZones/{managedZone}"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{managedZone}", URI.encode_path_segment(managed_zone.to_s))
      req_path = req_path.gsub("{+managedZone}", managed_zone.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?

      @client.execute(
        type: ManagedZone,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Sets the access control policy on the specified resource. Replaces any existing policy. Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED` errors.
    def set_iam_policy(
      resource : String,
      body : GoogleIamV1SetIamPolicyRequest? = nil,
    ) : GoogleIamV1Policy
      req_path = "dns/v1/{+resource}:setIamPolicy"
      req_path = req_path.gsub("{resource}", URI.encode_path_segment(resource.to_s))
      req_path = req_path.gsub("{+resource}", resource.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: GoogleIamV1Policy,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Creates a new ManagedZone. Note: While `dns.managedZones.create` is the baseline permission required to invoke this method, additional permissions are required if the managed zone configuration references other resources.
    def create(
      project : String,
      body : ManagedZone? = nil,
      client_operation_id : String? = nil,
    ) : ManagedZone
      req_path = "dns/v1/projects/{project}/managedZones"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?

      @client.execute(
        type: ManagedZone,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Deletes a previously created ManagedZone.
    def delete(
      project : String,
      managed_zone : String,
      client_operation_id : String? = nil,
    ) : Nil
      req_path = "dns/v1/projects/{project}/managedZones/{managedZone}"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{managedZone}", URI.encode_path_segment(managed_zone.to_s))
      req_path = req_path.gsub("{+managedZone}", managed_zone.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?

      @client.execute_raw(
        http_method: "DELETE",
        path: req_path,
        params: params,
        body: nil
      )
      nil
    end
  end
end
