# Generated by Google APIs Discovery Generator for dns (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Dns::V1
  class PoliciesService < GoogleApis::Service
    # Fetches the representation of an existing policy.
    def get(
      project : String,
      policy : String,
      client_operation_id : String? = nil,
    ) : Policy
      req_path = "dns/v1/projects/{project}/policies/{policy}"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{policy}", URI.encode_path_segment(policy.to_s))
      req_path = req_path.gsub("{+policy}", policy.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?

      @client.execute(
        type: Policy,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Updates an existing policy.
    def update(
      project : String,
      policy : String,
      body : Policy? = nil,
      client_operation_id : String? = nil,
    ) : PoliciesUpdateResponse
      req_path = "dns/v1/projects/{project}/policies/{policy}"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{policy}", URI.encode_path_segment(policy.to_s))
      req_path = req_path.gsub("{+policy}", policy.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?

      @client.execute(
        type: PoliciesUpdateResponse,
        http_method: "PUT",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Enumerates all policies associated with a project.
    def list(
      project : String,
      max_results : Int64? = nil,
      page_token : String? = nil,
    ) : PoliciesListResponse
      req_path = "dns/v1/projects/{project}/policies"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["maxResults"] = max_results unless max_results.nil?
      params["pageToken"] = page_token unless page_token.nil?

      @client.execute(
        type: PoliciesListResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Deletes a previously created policy. Fails if the policy is still being referenced by a network.
    def delete(
      project : String,
      policy : String,
      client_operation_id : String? = nil,
    ) : Nil
      req_path = "dns/v1/projects/{project}/policies/{policy}"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{policy}", URI.encode_path_segment(policy.to_s))
      req_path = req_path.gsub("{+policy}", policy.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?

      @client.execute_raw(
        http_method: "DELETE",
        path: req_path,
        params: params,
        body: nil
      )
      nil
    end

    # Applies a partial update to an existing policy.
    def patch(
      project : String,
      policy : String,
      body : Policy? = nil,
      client_operation_id : String? = nil,
    ) : PoliciesPatchResponse
      req_path = "dns/v1/projects/{project}/policies/{policy}"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{policy}", URI.encode_path_segment(policy.to_s))
      req_path = req_path.gsub("{+policy}", policy.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?

      @client.execute(
        type: PoliciesPatchResponse,
        http_method: "PATCH",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Creates a new policy.
    def create(
      project : String,
      body : Policy? = nil,
      client_operation_id : String? = nil,
    ) : Policy
      req_path = "dns/v1/projects/{project}/policies"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?

      @client.execute(
        type: Policy,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end
  end
end
