# Generated by Google APIs Discovery Generator for dns (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Dns::V1
  class ProjectsService < GoogleApis::Service
    # Fetches the representation of an existing Project.
    def get(
      project : String,
    ) : Project
      req_path = "dns/v1/projects/{project}"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new

      @client.execute(
        type: Project,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end
  end
end
