# Generated by Google APIs Discovery Generator for dns (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Dns::V1
  class ResourceRecordSetsService < GoogleApis::Service
    # Enumerates ResourceRecordSets that you have created but not yet deleted.
    def list(
      project : String,
      managed_zone : String,
      filter : String? = nil,
      max_results : Int64? = nil,
      name : String? = nil,
      page_token : String? = nil,
      type_param : String? = nil,
    ) : ResourceRecordSetsListResponse
      req_path = "dns/v1/projects/{project}/managedZones/{managedZone}/rrsets"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{managedZone}", URI.encode_path_segment(managed_zone.to_s))
      req_path = req_path.gsub("{+managedZone}", managed_zone.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["filter"] = filter unless filter.nil?
      params["maxResults"] = max_results unless max_results.nil?
      params["name"] = name unless name.nil?
      params["pageToken"] = page_token unless page_token.nil?
      params["type"] = type_param unless type_param.nil?

      @client.execute(
        type: ResourceRecordSetsListResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Fetches the representation of an existing ResourceRecordSet.
    def get(
      project : String,
      managed_zone : String,
      name : String,
      type_param : String,
      client_operation_id : String? = nil,
    ) : ResourceRecordSet
      req_path = "dns/v1/projects/{project}/managedZones/{managedZone}/rrsets/{name}/{type}"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{managedZone}", URI.encode_path_segment(managed_zone.to_s))
      req_path = req_path.gsub("{+managedZone}", managed_zone.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{type}", URI.encode_path_segment(type_param.to_s))
      req_path = req_path.gsub("{+type}", type_param.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?

      @client.execute(
        type: ResourceRecordSet,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Applies a partial update to an existing ResourceRecordSet.
    def patch(
      project : String,
      managed_zone : String,
      name : String,
      type_param : String,
      body : ResourceRecordSet? = nil,
      client_operation_id : String? = nil,
    ) : ResourceRecordSet
      req_path = "dns/v1/projects/{project}/managedZones/{managedZone}/rrsets/{name}/{type}"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{managedZone}", URI.encode_path_segment(managed_zone.to_s))
      req_path = req_path.gsub("{+managedZone}", managed_zone.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{type}", URI.encode_path_segment(type_param.to_s))
      req_path = req_path.gsub("{+type}", type_param.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?

      @client.execute(
        type: ResourceRecordSet,
        http_method: "PATCH",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Deletes a previously created ResourceRecordSet.
    def delete(
      project : String,
      managed_zone : String,
      name : String,
      type_param : String,
      client_operation_id : String? = nil,
    ) : ResourceRecordSetsDeleteResponse
      req_path = "dns/v1/projects/{project}/managedZones/{managedZone}/rrsets/{name}/{type}"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{managedZone}", URI.encode_path_segment(managed_zone.to_s))
      req_path = req_path.gsub("{+managedZone}", managed_zone.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{name}", URI.encode_path_segment(name.to_s))
      req_path = req_path.gsub("{+name}", name.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{type}", URI.encode_path_segment(type_param.to_s))
      req_path = req_path.gsub("{+type}", type_param.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?

      @client.execute(
        type: ResourceRecordSetsDeleteResponse,
        http_method: "DELETE",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Creates a new ResourceRecordSet.
    def create(
      project : String,
      managed_zone : String,
      body : ResourceRecordSet? = nil,
      client_operation_id : String? = nil,
    ) : ResourceRecordSet
      req_path = "dns/v1/projects/{project}/managedZones/{managedZone}/rrsets"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{managedZone}", URI.encode_path_segment(managed_zone.to_s))
      req_path = req_path.gsub("{+managedZone}", managed_zone.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = ::Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?

      @client.execute(
        type: ResourceRecordSet,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end
  end
end
