# Generated by Google APIs Discovery Generator for dns (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Dns::V1
  class ResponsePoliciesService < GoogleApis::Service
    # Enumerates all Response Policies associated with a project.
    def list(
      project : String,
      max_results : Int64? = nil,
      page_token : String? = nil,
    ) : ResponsePoliciesListResponse
      req_path = "dns/v1/projects/{project}/responsePolicies"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["maxResults"] = max_results unless max_results.nil?
      params["pageToken"] = page_token unless page_token.nil?

      @client.execute(
        type: ResponsePoliciesListResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Updates an existing Response Policy.
    def update(
      project : String,
      response_policy : String,
      body : ResponsePolicy? = nil,
      client_operation_id : String? = nil,
    ) : ResponsePoliciesUpdateResponse
      req_path = "dns/v1/projects/{project}/responsePolicies/{responsePolicy}"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{responsePolicy}", URI.encode_path_segment(response_policy.to_s))
      req_path = req_path.gsub("{+responsePolicy}", response_policy.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?

      @client.execute(
        type: ResponsePoliciesUpdateResponse,
        http_method: "PUT",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Applies a partial update to an existing Response Policy.
    def patch(
      project : String,
      response_policy : String,
      body : ResponsePolicy? = nil,
      client_operation_id : String? = nil,
    ) : ResponsePoliciesPatchResponse
      req_path = "dns/v1/projects/{project}/responsePolicies/{responsePolicy}"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{responsePolicy}", URI.encode_path_segment(response_policy.to_s))
      req_path = req_path.gsub("{+responsePolicy}", response_policy.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?

      @client.execute(
        type: ResponsePoliciesPatchResponse,
        http_method: "PATCH",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Deletes a previously created Response Policy. Fails if the response policy is non-empty or still being referenced by a network.
    def delete(
      project : String,
      response_policy : String,
      client_operation_id : String? = nil,
    ) : Nil
      req_path = "dns/v1/projects/{project}/responsePolicies/{responsePolicy}"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{responsePolicy}", URI.encode_path_segment(response_policy.to_s))
      req_path = req_path.gsub("{+responsePolicy}", response_policy.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?

      @client.execute_raw(
        http_method: "DELETE",
        path: req_path,
        params: params,
        body: nil
      )
      nil
    end

    # Fetches the representation of an existing Response Policy.
    def get(
      project : String,
      response_policy : String,
      client_operation_id : String? = nil,
    ) : ResponsePolicy
      req_path = "dns/v1/projects/{project}/responsePolicies/{responsePolicy}"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{responsePolicy}", URI.encode_path_segment(response_policy.to_s))
      req_path = req_path.gsub("{+responsePolicy}", response_policy.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?

      @client.execute(
        type: ResponsePolicy,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Creates a new Response Policy
    def create(
      project : String,
      body : ResponsePolicy? = nil,
      client_operation_id : String? = nil,
    ) : ResponsePolicy
      req_path = "dns/v1/projects/{project}/responsePolicies"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?

      @client.execute(
        type: ResponsePolicy,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end
  end
end
