# Generated by Google APIs Discovery Generator for dns (v1)
# Do not edit directly.

require "uri"
require "../../service"
require "./types"

module GoogleApis::Dns::V1
  class ResponsePolicyRulesService < GoogleApis::Service
    # Fetches the representation of an existing Response Policy Rule.
    def get(
      project : String,
      response_policy : String,
      response_policy_rule : String,
      client_operation_id : String? = nil,
    ) : ResponsePolicyRule
      req_path = "dns/v1/projects/{project}/responsePolicies/{responsePolicy}/rules/{responsePolicyRule}"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{responsePolicy}", URI.encode_path_segment(response_policy.to_s))
      req_path = req_path.gsub("{+responsePolicy}", response_policy.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{responsePolicyRule}", URI.encode_path_segment(response_policy_rule.to_s))
      req_path = req_path.gsub("{+responsePolicyRule}", response_policy_rule.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?

      @client.execute(
        type: ResponsePolicyRule,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Applies a partial update to an existing Response Policy Rule.
    def patch(
      project : String,
      response_policy : String,
      response_policy_rule : String,
      body : ResponsePolicyRule? = nil,
      client_operation_id : String? = nil,
    ) : ResponsePolicyRulesPatchResponse
      req_path = "dns/v1/projects/{project}/responsePolicies/{responsePolicy}/rules/{responsePolicyRule}"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{responsePolicy}", URI.encode_path_segment(response_policy.to_s))
      req_path = req_path.gsub("{+responsePolicy}", response_policy.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{responsePolicyRule}", URI.encode_path_segment(response_policy_rule.to_s))
      req_path = req_path.gsub("{+responsePolicyRule}", response_policy_rule.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?

      @client.execute(
        type: ResponsePolicyRulesPatchResponse,
        http_method: "PATCH",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Enumerates all Response Policy Rules associated with a project.
    def list(
      project : String,
      response_policy : String,
      max_results : Int64? = nil,
      page_token : String? = nil,
    ) : ResponsePolicyRulesListResponse
      req_path = "dns/v1/projects/{project}/responsePolicies/{responsePolicy}/rules"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{responsePolicy}", URI.encode_path_segment(response_policy.to_s))
      req_path = req_path.gsub("{+responsePolicy}", response_policy.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["maxResults"] = max_results unless max_results.nil?
      params["pageToken"] = page_token unless page_token.nil?

      @client.execute(
        type: ResponsePolicyRulesListResponse,
        http_method: "GET",
        path: req_path,
        params: params,
        body: nil
      )
    end

    # Updates an existing Response Policy Rule.
    def update(
      project : String,
      response_policy : String,
      response_policy_rule : String,
      body : ResponsePolicyRule? = nil,
      client_operation_id : String? = nil,
    ) : ResponsePolicyRulesUpdateResponse
      req_path = "dns/v1/projects/{project}/responsePolicies/{responsePolicy}/rules/{responsePolicyRule}"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{responsePolicy}", URI.encode_path_segment(response_policy.to_s))
      req_path = req_path.gsub("{+responsePolicy}", response_policy.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{responsePolicyRule}", URI.encode_path_segment(response_policy_rule.to_s))
      req_path = req_path.gsub("{+responsePolicyRule}", response_policy_rule.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?

      @client.execute(
        type: ResponsePolicyRulesUpdateResponse,
        http_method: "PUT",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Creates a new Response Policy Rule.
    def create(
      project : String,
      response_policy : String,
      body : ResponsePolicyRule? = nil,
      client_operation_id : String? = nil,
    ) : ResponsePolicyRule
      req_path = "dns/v1/projects/{project}/responsePolicies/{responsePolicy}/rules"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{responsePolicy}", URI.encode_path_segment(response_policy.to_s))
      req_path = req_path.gsub("{+responsePolicy}", response_policy.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?

      @client.execute(
        type: ResponsePolicyRule,
        http_method: "POST",
        path: req_path,
        params: params,
        body: body.try(&.to_json)
      )
    end

    # Deletes a previously created Response Policy Rule.
    def delete(
      project : String,
      response_policy : String,
      response_policy_rule : String,
      client_operation_id : String? = nil,
    ) : Nil
      req_path = "dns/v1/projects/{project}/responsePolicies/{responsePolicy}/rules/{responsePolicyRule}"
      req_path = req_path.gsub("{project}", URI.encode_path_segment(project.to_s))
      req_path = req_path.gsub("{+project}", project.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{responsePolicy}", URI.encode_path_segment(response_policy.to_s))
      req_path = req_path.gsub("{+responsePolicy}", response_policy.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))
      req_path = req_path.gsub("{responsePolicyRule}", URI.encode_path_segment(response_policy_rule.to_s))
      req_path = req_path.gsub("{+responsePolicyRule}", response_policy_rule.to_s.split('/').map { |segment| URI.encode_path_segment(segment) }.join('/'))

      params = Hash(String, String | Array(String) | Int32 | Int64 | Bool | Nil).new
      params["clientOperationId"] = client_operation_id unless client_operation_id.nil?

      @client.execute_raw(
        http_method: "DELETE",
        path: req_path,
        params: params,
        body: nil
      )
      nil
    end
  end
end
