# Generated by Google APIs Discovery Generator for dns (v1)
# Do not edit directly.

require "./types"
require "./client"
require "./changes_service"
require "./projects_service"
require "./resource_record_sets_service"
require "./policies_service"
require "./dns_keys_service"
require "./response_policy_rules_service"
require "./managed_zone_operations_service"
require "./managed_zones_service"
require "./response_policies_service"

module GoogleApis::Dns::V1
end
